/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arunaedu.main;

import static com.anuraedu.common.SQ.LIKESEARCH;
import static com.anuraedu.common.SQ.PVTSEARCH4;
import static com.anuraedu.common.SQ.SAVE;
import static com.anuraedu.common.SQ.SEARCH;
import static com.anuraedu.common.SQ.UPDATE;
import static com.anuraedu.common.SQ.getResult;
import com.anuraedu.db.DB;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class AcademicDataInput extends javax.swing.JInternalFrame {

    DefaultTableModel dtm1;
    String ExamScoreDef = "0";

    public AcademicDataInput() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI) this.getUI();
        bif.setNorthPane(null);
        txt_examScore.setText(ExamScoreDef);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_examScore = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        rad_active = new javax.swing.JRadioButton();
        rad_inactive = new javax.swing.JRadioButton();
        txt_examStudentid = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_save = new javax.swing.JButton();
        txt_examid = new javax.swing.JTextField();
        cbox_1 = new javax.swing.JCheckBox();
        cbox_2 = new javax.swing.JCheckBox();
        cbox_4 = new javax.swing.JCheckBox();
        cbox_3 = new javax.swing.JCheckBox();
        btn_update = new javax.swing.JButton();
        btn_examResults = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_assignmentScore = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        rad_active2 = new javax.swing.JRadioButton();
        rad_inactive2 = new javax.swing.JRadioButton();
        txt_assignmentStudentid = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable_2 = new javax.swing.JTable();
        btn_save2 = new javax.swing.JButton();
        txt_assignmentid = new javax.swing.JTextField();
        cbox_6 = new javax.swing.JCheckBox();
        cbox_8 = new javax.swing.JCheckBox();
        cbox_7 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_NoteStudentid = new javax.swing.JTextField();
        txt_NoteClassid = new javax.swing.JTextField();
        btn_save3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1670, 1040));

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Exam Data Input", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 76, 76));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Exam ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 76, 76));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Student ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 76, 76));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Score");

        txt_examScore.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_examScore.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_examScore.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_examScoreKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(76, 76, 76));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Attend Status");

        buttonGroup1.add(rad_active);
        rad_active.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_active.setSelected(true);
        rad_active.setText("Active");

        buttonGroup1.add(rad_inactive);
        rad_inactive.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_inactive.setText("Inactive");

        txt_examStudentid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_examStudentid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_examStudentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_examStudentidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_examStudentidKeyTyped(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam ID", "Description", "Class ID"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable3);

        jTabbedPane1.addTab("Exam ID Search", jScrollPane1);

        jTable_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First name", "Last name", "NIC", "Contact No.", "Address", "Email", "Gender", "DOB", "FTHR.Fname", "FTHR.Lname", "FTHR.ContactNo.", "MTH.Fname", "MTH.Lname", "MTH.ContactNo.", "GDN.Fname", "GDN.Lname", "GDN.ContactNo.", "Status"
            }
        ));
        jTable_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_1);

        jTabbedPane1.addTab("Student ID Search", jScrollPane2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exam ID", "Student ID", "Score", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jTabbedPane1.addTab("Exam Results", jScrollPane3);

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        txt_examid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_examid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_examid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_examidKeyReleased(evt);
            }
        });

        buttonGroup2.add(cbox_1);
        cbox_1.setText("suggestions");
        cbox_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(cbox_2);
        cbox_2.setText("show all");
        cbox_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(cbox_4);
        cbox_4.setText("show all");
        cbox_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_4ActionPerformed(evt);
            }
        });

        buttonGroup3.add(cbox_3);
        cbox_3.setText("suggestions");
        cbox_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_3ActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_examResults.setText("View Exam Resutls");
        btn_examResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_examResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad_active)
                        .addGap(18, 18, 18)
                        .addComponent(rad_inactive))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_examStudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_examid, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_examScore, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbox_1)
                            .addComponent(cbox_2)
                            .addComponent(cbox_3)
                            .addComponent(cbox_4))))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_examResults, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_examResults, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_examid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbox_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbox_2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_examStudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_examScore, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rad_active)
                                    .addComponent(rad_inactive)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbox_3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbox_4)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assignment Data Input", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 76, 76));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Assignment ID");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(76, 76, 76));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Student ID");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(76, 76, 76));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Score");

        txt_assignmentScore.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_assignmentScore.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(76, 76, 76));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Status and Time");

        rad_active2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_active2.setSelected(true);
        rad_active2.setText("Active");

        rad_inactive2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_inactive2.setText("Inactive");

        txt_assignmentStudentid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_assignmentStudentid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_assignmentStudentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_assignmentStudentidKeyReleased(evt);
            }
        });

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assignment ID", "Class ID", "Description"
            }
        ));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable5);

        jTabbedPane2.addTab("Assignment ID Search", jScrollPane4);

        jTable_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First name", "Last name", "NIC", "Contact No.", "Address", "Email", "Gender", "DOB", "FTHR.Fname", "FTHR.Lname", "FTHR.ContactNo.", "MTH.Fname", "MTH.Lname", "MTH.ContactNo.", "GDN.Fname", "GDN.Lname", "GDN.ContactNo.", "Status"
            }
        ));
        jTable_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_2MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jTable_2);

        jTabbedPane2.addTab("Student ID Search", jScrollPane6);

        btn_save2.setText("Save");
        btn_save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save2ActionPerformed(evt);
            }
        });

        txt_assignmentid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_assignmentid.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        buttonGroup4.add(cbox_6);
        cbox_6.setText("show all");
        cbox_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_6ActionPerformed(evt);
            }
        });

        buttonGroup5.add(cbox_8);
        cbox_8.setText("show all");
        cbox_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_8ActionPerformed(evt);
            }
        });

        buttonGroup5.add(cbox_7);
        cbox_7.setText("suggestions");
        cbox_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_assignmentid, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad_active2)
                        .addGap(18, 18, 18)
                        .addComponent(rad_inactive2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_assignmentScore, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_assignmentStudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbox_6)
                    .addComponent(cbox_7)
                    .addComponent(cbox_8))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_save2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_assignmentid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbox_6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_assignmentStudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbox_7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbox_8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_assignmentScore, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rad_active2)
                            .addComponent(rad_inactive2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_save2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Note Cheking", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(76, 76, 76));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Class ID");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(76, 76, 76));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Student ID");

        txt_NoteStudentid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_NoteStudentid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_NoteStudentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_NoteStudentidKeyReleased(evt);
            }
        });

        txt_NoteClassid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_NoteClassid.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btn_save3.setText("Save");
        btn_save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_save3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_NoteClassid, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_NoteStudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1153, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_NoteClassid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NoteStudentid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_save3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if (!txt_examid.getText().equals("") && !txt_examStudentid.getText().equals("") && !txt_examScore.getText().equals("")) {
            int status = (rad_active.isSelected()) ? 1 : 0;
            try {
                DB.push("insert into student_exam (id_exam,id_student,score,attends_status) values ('"
                        + txt_examid.getText() + "','"
                        + txt_examStudentid.getText() + "','"
                        + Double.parseDouble(txt_examScore.getText()) + "','"
                        + status + "')");
                clearExamFileds();
                JOptionPane.showMessageDialog(this, "Saved !");
            } catch (Exception e) {
                e.printStackTrace();
            }

        } else {
            JOptionPane.showMessageDialog(this, "FILL ALL FIELDS !");
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save2ActionPerformed
        try {
            int status = (rad_active2.isSelected()) ? 1 : 0;
            DB.push("insert into student_assignment (id_student,id_assignment,score,submit_status,submited_datetime) values('"+
                    txt_assignmentStudentid.getText()+"','"+
                    txt_assignmentid.getText()+"','"+
                    Double.parseDouble(txt_assignmentScore.getText())+"','"+
                    status+"',now())");
            
            JOptionPane.showMessageDialog(this, "Saved !");
            txt_assignmentStudentid.setText("");
            txt_assignmentScore.setText("");
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_save2ActionPerformed

    private void btn_save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save3ActionPerformed
        try {
            DB.push("insert into student_notecheck (id_class,id_student,date) values('"+
                    txt_NoteClassid.getText()+"','"+
                    txt_NoteStudentid.getText()+"',now())");
           JOptionPane.showMessageDialog(this, "Saved !");
           txt_NoteStudentid.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_save3ActionPerformed

    private void cbox_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_6ActionPerformed
      jTabbedPane2.setSelectedIndex(0);
        try {
          ResultSet rs = DB.search("select id_assignment, id_class, description from shedule_assignment");
           
            while (rs.next()) {

                String id_assignment = rs.getString("id_assignment");
                String id_class = rs.getString("id_class");
                String description = rs.getString("description");

                Vector v = new Vector();

                v.add(id_assignment);
                v.add(id_class);
                v.add(description);

                dtm1 = (DefaultTableModel) jTable5.getModel();
                dtm1.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbox_6ActionPerformed

    private void cbox_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_2ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        removeAllRows(jTable3);
        examSearch(0);
    }//GEN-LAST:event_cbox_2ActionPerformed

    private void cbox_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_4ActionPerformed
        removeAllRows(jTable_1);
        if (cbox_4.isSelected()) {
            studentAllSearch(jTable_1);
        }
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_cbox_4ActionPerformed

    private void cbox_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_8ActionPerformed
        removeAllRows(jTable_2);
        if (cbox_8.isSelected()) {
            studentAllSearch(jTable_2);
        }
        jTabbedPane2.setSelectedIndex(1);


    }//GEN-LAST:event_cbox_8ActionPerformed

    private void cbox_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_1ActionPerformed

    }//GEN-LAST:event_cbox_1ActionPerformed

    private void cbox_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_3ActionPerformed

    }//GEN-LAST:event_cbox_3ActionPerformed

    private void cbox_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_7ActionPerformed

    }//GEN-LAST:event_cbox_7ActionPerformed

    private void txt_examidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_examidKeyReleased
        if (cbox_1.isSelected()) {
            removeAllRows(jTable3);
            examSearch(1);
        }
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_txt_examidKeyReleased

    private void txt_examStudentidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_examStudentidKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_examStudentidKeyTyped

    private void txt_examStudentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_examStudentidKeyReleased
        jTabbedPane1.setSelectedIndex(1);
        removeAllRows(jTable_1);
        if (cbox_3.isSelected()) {
            studentLetterSearch(txt_examStudentid, jTable_1);
        }
    }//GEN-LAST:event_txt_examStudentidKeyReleased

    private void txt_assignmentStudentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_assignmentStudentidKeyReleased
        jTabbedPane2.setSelectedIndex(1);
        removeAllRows(jTable_2);
        if (cbox_7.isSelected()) {
            studentLetterSearch(txt_assignmentStudentid, jTable_2);
        }
    }//GEN-LAST:event_txt_assignmentStudentidKeyReleased

    private void txt_NoteStudentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NoteStudentidKeyReleased

    }//GEN-LAST:event_txt_NoteStudentidKeyReleased

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        txt_examid.setText((String) jTable3.getValueAt(jTable3.getSelectedRow(), 0));
    }//GEN-LAST:event_jTable3MouseClicked

    private void jTable_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_1MouseClicked
        txt_examStudentid.setText((String) jTable_1.getValueAt(jTable_1.getSelectedRow(), 0));
    }//GEN-LAST:event_jTable_1MouseClicked

    private void txt_examScoreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_examScoreKeyTyped

    }//GEN-LAST:event_txt_examScoreKeyTyped

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
             int status = (rad_active.isSelected()) ? 1 : 0;
            DB.push("update student_exam set score='"+
                    Double.parseDouble(txt_examScore.getText())+"', status'"+
                    status+"' where id_exam='"+
                    txt_examid.getText()+"'");
        } catch (Exception ex) {
           ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_examResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_examResultsActionPerformed
        try {
            ResultSet rs = DB.search("select id_exam, id_student, score,attends_status from student_exam");
            while (rs.next()) {

                String id_exam = rs.getString("id_exam");
                String id_student = rs.getString("id_student");
                String score = String.valueOf(rs.getDouble("score"));
                String attends_status = null;
                if (rs.getBoolean("attends_status")) {
                    attends_status = "presented";
                } else {
                    attends_status = "absented";
                }

                Vector v = new Vector();

                v.add(id_exam);
                v.add(id_student);
                v.add(score);
                v.add(attends_status);

                dtm1 = (DefaultTableModel) jTable1.getModel();
                dtm1.addRow(v);
            }
            jTabbedPane1.setSelectedIndex(2);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_examResultsActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        txt_examid.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        try {
            ResultSet rs = DB.search("select id_student, score,attends_status from student_exam where id_exam='"
                    + txt_examid.getText() + "'");
            if (rs.next()) {
                txt_examStudentid.setText(rs.getString("id_student"));
                txt_examScore.setText(String.valueOf(rs.getDouble("score")));
                if (rs.getBoolean("attends_status")) {
                    rad_active.setSelected(true);
                }else{
                    rad_inactive.setSelected(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        txt_assignmentid.setText((String) jTable5.getValueAt(jTable5.getSelectedRow(), 0));
    }//GEN-LAST:event_jTable5MouseClicked

    private void jTable_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_2MouseClicked
        txt_assignmentStudentid.setText((String) jTable_2.getValueAt(jTable_2.getSelectedRow(), 0));
    }//GEN-LAST:event_jTable_2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_examResults;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_save2;
    private javax.swing.JButton btn_save3;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JCheckBox cbox_1;
    private javax.swing.JCheckBox cbox_2;
    private javax.swing.JCheckBox cbox_3;
    private javax.swing.JCheckBox cbox_4;
    private javax.swing.JCheckBox cbox_6;
    private javax.swing.JCheckBox cbox_7;
    private javax.swing.JCheckBox cbox_8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable_1;
    private javax.swing.JTable jTable_2;
    private javax.swing.JRadioButton rad_active;
    private javax.swing.JRadioButton rad_active2;
    private javax.swing.JRadioButton rad_inactive;
    private javax.swing.JRadioButton rad_inactive2;
    private javax.swing.JTextField txt_NoteClassid;
    private javax.swing.JTextField txt_NoteStudentid;
    private javax.swing.JTextField txt_assignmentScore;
    private javax.swing.JTextField txt_assignmentStudentid;
    private javax.swing.JTextField txt_assignmentid;
    private javax.swing.JTextField txt_examScore;
    private javax.swing.JTextField txt_examStudentid;
    private javax.swing.JTextField txt_examid;
    // End of variables declaration//GEN-END:variables

    private void studentLetterSearch(JTextField jt, JTable jtb) {
        try {
            LIKESEARCH("student", "id_student", jt.getText());
            fillStudentTable(jtb);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void studentAllSearch(JTable jt) {
        try {
            SEARCH("student");
        } catch (Exception e) {
            e.printStackTrace();
        }
        fillStudentTable(jt);
    }

    private void fillStudentTable(JTable jt) {

        try {

            ResultSet rs = getResult();
            while (rs.next()) {

                String id_student = rs.getString("id_student");
                String fname = rs.getString("fname");
                String lname = rs.getString("lname");
                String nic = rs.getString("nic");
                String contact_no = rs.getString("contact_no");
                String address = rs.getString("address");
                String email = rs.getString("email");
                String gender = rs.getString("gender");
                String dob = rs.getString("dob");
                String father_fname = rs.getString("father_fname");
                String father_lname = rs.getString("father_lname");
                String father_ctn = rs.getString("father_ctn");
                String mother_fname = rs.getString("mother_fname");
                String mother_lname = rs.getString("mother_lname");
                String mother_ctn = rs.getString("mother_ctn");
                String guardian_fname = rs.getString("guardian_fname");
                String guardian_lname = rs.getString("guardian_lname");
                String guardian_ctn = rs.getString("guardian_ctn");

                boolean status = rs.getBoolean("status");

                Vector v = new Vector();

                v.add(id_student);
                v.add(fname);
                v.add(lname);
                v.add(nic);
                v.add(contact_no);
                v.add(address);
                v.add(email);
                v.add(gender);
                v.add(dob);
                v.add(father_fname);
                v.add(father_lname);
                v.add(father_ctn);
                v.add(mother_fname);
                v.add(mother_lname);
                v.add(mother_ctn);
                v.add(guardian_fname);
                v.add(guardian_lname);
                v.add(guardian_ctn);

                if (status) {
                    v.add("Active");
                } else {
                    v.add("Inactive");
                }

                dtm1 = (DefaultTableModel) jt.getModel();

                dtm1.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void removeAllRows(JTable j) {

        for (int i = j.getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) j.getModel()).removeRow(i);
        }

    }

    private void fillExamTable() {
        try {

            ResultSet rs = getResult();
            while (rs.next()) {

                String id_exam = rs.getString("id_exam");
                String description = rs.getString("description");
                String id_class = rs.getString("id_class");

                Vector v = new Vector();

                v.add(id_exam);
                v.add(description);
                v.add(id_class);

                dtm1 = (DefaultTableModel) jTable3.getModel();
                dtm1.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void examSearch(int type) {
        try {
            if (type == 0) {
                SEARCH("shedule_exam");
                fillExamTable();
            } else if (type == 1) {
                LIKESEARCH("shedule_exam", "id_exam", txt_examid.getText());
                fillExamTable();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void clearExamFileds() {
        txt_examStudentid.setText("");
        txt_examScore.setText("0");
        rad_active.setSelected(true);
    }

}
