/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arunaedu.main;

import static com.anuraedu.common.SQ.LIKESEARCH;
import static com.anuraedu.common.SQ.PVTSEARCH;
import static com.anuraedu.common.SQ.PVTSEARCH2;
import static com.anuraedu.common.SQ.SAVE;
import static com.anuraedu.common.SQ.SEARCH;
import static com.anuraedu.common.SQ.UPDATE;
import static com.anuraedu.common.SQ.getResult;
import com.anuraedu.db.DB;
import static com.arunaedu.main.StudentRegistration.isValid;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class LecturerRegistration extends javax.swing.JInternalFrame {

    ArrayList<JTextField> jf;
    ArrayList<String> defaultText,id,mylist;
    String replacepath,dob,prevText;
    DefaultTableModel dtm1;
    
    


    ImageIcon icn4 = new ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\ArunaEdu\\src\\com\\anuraedu\\icons\\icn4.png");

    public LecturerRegistration() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI) this.getUI();
        bif.setNorthPane(null);

        addDefaultTextToList();
        addTextFieldsToList();
        setDefaultText();
        setDefaultTextField();
        generateLecturerId();

        jComboBox_gender.addItem("Male");
        jComboBox_gender.addItem("Female");
        jComboBox_gender.addItem("Other");
        
        lbl_image.setIcon(icn4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_main = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        panel_image = new javax.swing.JPanel();
        lbl_image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_lecturerid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_lname = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser_dob = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jComboBox_gender = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_cno1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        rad_active = new javax.swing.JRadioButton();
        rad_inactive = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_cno2 = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_resetMain = new javax.swing.JLabel();
        btn_goToSearch = new javax.swing.JLabel();
        btn_delete = new javax.swing.JLabel();
        btn_update = new javax.swing.JLabel();
        btn_save = new javax.swing.JLabel();
        panel_search = new javax.swing.JPanel();
        txt_searchBox = new javax.swing.JTextField();
        cbox_lecturerId = new javax.swing.JCheckBox();
        cbox_nic = new javax.swing.JCheckBox();
        cbox_showSuggetions = new javax.swing.JCheckBox();
        cbox_fname = new javax.swing.JCheckBox();
        btn_searchInSearch = new javax.swing.JLabel();
        btn_editSelected = new javax.swing.JLabel();
        btn_editSelected1 = new javax.swing.JLabel();
        btn_showAll = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1670, 1040));

        jTabbedPane1.setBackground(new java.awt.Color(178, 230, 245));
        jTabbedPane1.setOpaque(true);

        panel_main.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 195, 219)));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(76, 76, 76));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("+ Profile Pictuer");

        panel_image.setBackground(new java.awt.Color(178, 230, 245));
        panel_image.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 1, true));

        lbl_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_imageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_imageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_imageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_imageLayout = new javax.swing.GroupLayout(panel_image);
        panel_image.setLayout(panel_imageLayout);
        panel_imageLayout.setHorizontalGroup(
            panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_imageLayout.setVerticalGroup(
            panel_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_imageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 76, 76));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Lecturer ID");

        txt_lecturerid.setBackground(new java.awt.Color(178, 230, 245));
        txt_lecturerid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_lecturerid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_lecturerid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_lectureridFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_lectureridFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 76, 76));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Name");

        txt_fname.setBackground(new java.awt.Color(178, 230, 245));
        txt_fname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_fname.setForeground(new java.awt.Color(124, 124, 124));
        txt_fname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_fname.setToolTipText("First name");
        txt_fname.setVerifyInputWhenFocusTarget(false);
        txt_fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_fnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_fnameFocusLost(evt);
            }
        });
        txt_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fnameActionPerformed(evt);
            }
        });

        txt_lname.setBackground(new java.awt.Color(178, 230, 245));
        txt_lname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_lname.setForeground(new java.awt.Color(124, 124, 124));
        txt_lname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_lname.setToolTipText("Last name");
        txt_lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_lnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_lnameFocusLost(evt);
            }
        });
        txt_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lnameActionPerformed(evt);
            }
        });

        txt_nic.setBackground(new java.awt.Color(178, 230, 245));
        txt_nic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nic.setForeground(new java.awt.Color(124, 124, 124));
        txt_nic.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nic.setToolTipText("Nic");
        txt_nic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nicFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nicFocusLost(evt);
            }
        });
        txt_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nicActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 76, 76));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("NIC");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(76, 76, 76));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("DOB");

        jDateChooser_dob.setBackground(new java.awt.Color(178, 230, 245));
        jDateChooser_dob.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(76, 76, 76));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Gender");

        jComboBox_gender.setBackground(new java.awt.Color(178, 230, 245));
        jComboBox_gender.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(76, 76, 76));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Contact Number 1.");

        txt_cno1.setBackground(new java.awt.Color(178, 230, 245));
        txt_cno1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cno1.setForeground(new java.awt.Color(124, 124, 124));
        txt_cno1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_cno1.setToolTipText("Contact number");
        txt_cno1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cno1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cno1FocusLost(evt);
            }
        });
        txt_cno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cno1ActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(20, 125, 177));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Lecturer Registration");
        jLabel11.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_lecturerid)
                    .addComponent(txt_nic)
                    .addComponent(txt_cno1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(panel_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 265, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_lname)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_image, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_lecturerid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cno1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 195, 219)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(76, 76, 76));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Address");

        txt_address.setBackground(new java.awt.Color(178, 230, 245));
        txt_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_address.setForeground(new java.awt.Color(124, 124, 124));
        txt_address.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_address.setToolTipText("Email");
        txt_address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_addressFocusLost(evt);
            }
        });
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });

        rad_active.setBackground(new java.awt.Color(218, 243, 250));
        buttonGroup2.add(rad_active);
        rad_active.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rad_active.setSelected(true);
        rad_active.setText("Active");

        rad_inactive.setBackground(new java.awt.Color(218, 243, 250));
        buttonGroup2.add(rad_inactive);
        rad_inactive.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rad_inactive.setText("Inactive");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(76, 76, 76));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Lecturer status");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 76, 76));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Contact number 2.");

        txt_cno2.setBackground(new java.awt.Color(178, 230, 245));
        txt_cno2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_cno2.setForeground(new java.awt.Color(124, 124, 124));
        txt_cno2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_cno2.setToolTipText("Address");
        txt_cno2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_cno2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cno2FocusLost(evt);
            }
        });
        txt_cno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cno2ActionPerformed(evt);
            }
        });

        txt_email.setBackground(new java.awt.Color(178, 230, 245));
        txt_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_email.setForeground(new java.awt.Color(124, 124, 124));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_email.setToolTipText("Email");
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(76, 76, 76));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Email");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_address)
                    .addComponent(txt_cno2)
                    .addComponent(txt_email)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rad_active)
                                .addGap(26, 26, 26)
                                .addComponent(rad_inactive))
                            .addComponent(jLabel5))
                        .addGap(0, 403, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cno2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_active)
                    .addComponent(rad_inactive))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 195, 219)));

        btn_resetMain.setBackground(new java.awt.Color(69, 141, 152));
        btn_resetMain.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_resetMain.setForeground(new java.awt.Color(255, 255, 255));
        btn_resetMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_resetMain.setText("Reset");
        btn_resetMain.setOpaque(true);
        btn_resetMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_resetMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_resetMainMouseExited(evt);
            }
        });

        btn_goToSearch.setBackground(new java.awt.Color(69, 141, 152));
        btn_goToSearch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_goToSearch.setForeground(new java.awt.Color(255, 255, 255));
        btn_goToSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_goToSearch.setText("Go to Search");
        btn_goToSearch.setOpaque(true);
        btn_goToSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_goToSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_goToSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_goToSearchMouseExited(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(69, 141, 152));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_delete.setText("Delete");
        btn_delete.setOpaque(true);
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deleteMouseExited(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(69, 141, 152));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_update.setText("Update");
        btn_update.setOpaque(true);
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_updateMouseExited(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(69, 141, 152));
        btn_save.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_save.setText("Save");
        btn_save.setOpaque(true);
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_saveMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_goToSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(btn_resetMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_goToSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_resetMain, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_mainLayout = new javax.swing.GroupLayout(panel_main);
        panel_main.setLayout(panel_mainLayout);
        panel_mainLayout.setHorizontalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_mainLayout.setVerticalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Main", panel_main);

        panel_search.setBackground(new java.awt.Color(255, 255, 255));

        txt_searchBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_searchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchBoxKeyReleased(evt);
            }
        });

        buttonGroup1.add(cbox_lecturerId);
        cbox_lecturerId.setSelected(true);
        cbox_lecturerId.setText("Lecturer ID");
        cbox_lecturerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_lecturerIdActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbox_nic);
        cbox_nic.setText("NIC");

        cbox_showSuggetions.setText("Show Suggestions");
        cbox_showSuggetions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_showSuggetionsActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbox_fname);
        cbox_fname.setText("Fname");
        cbox_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_fnameActionPerformed(evt);
            }
        });

        btn_searchInSearch.setBackground(new java.awt.Color(69, 141, 152));
        btn_searchInSearch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_searchInSearch.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchInSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_searchInSearch.setText("Search");
        btn_searchInSearch.setOpaque(true);
        btn_searchInSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchInSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchInSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchInSearchMouseExited(evt);
            }
        });

        btn_editSelected.setBackground(new java.awt.Color(69, 141, 152));
        btn_editSelected.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_editSelected.setForeground(new java.awt.Color(255, 255, 255));
        btn_editSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editSelected.setText("Edit Selected");
        btn_editSelected.setOpaque(true);
        btn_editSelected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editSelectedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editSelectedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editSelectedMouseExited(evt);
            }
        });

        btn_editSelected1.setBackground(new java.awt.Color(69, 141, 152));
        btn_editSelected1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_editSelected1.setForeground(new java.awt.Color(255, 255, 255));
        btn_editSelected1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editSelected1.setText("Back to the Main");
        btn_editSelected1.setOpaque(true);
        btn_editSelected1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editSelected1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editSelected1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editSelected1MouseExited(evt);
            }
        });

        btn_showAll.setBackground(new java.awt.Color(69, 141, 152));
        btn_showAll.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_showAll.setForeground(new java.awt.Color(255, 255, 255));
        btn_showAll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_showAll.setText("Show All");
        btn_showAll.setOpaque(true);
        btn_showAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showAllMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_showAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_showAllMouseExited(evt);
            }
        });

        Table_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lecturer ID", "First name", "Last name", "NIC", "DOB", "Contact No.1", "Contact No.2", "Address", "Email", "Gender", "Status"
            }
        ));
        jScrollPane1.setViewportView(Table_1);

        javax.swing.GroupLayout panel_searchLayout = new javax.swing.GroupLayout(panel_search);
        panel_search.setLayout(panel_searchLayout);
        panel_searchLayout.setHorizontalGroup(
            panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1629, Short.MAX_VALUE)
                    .addGroup(panel_searchLayout.createSequentialGroup()
                        .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_searchLayout.createSequentialGroup()
                                .addComponent(cbox_lecturerId)
                                .addGap(18, 18, 18)
                                .addComponent(cbox_nic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbox_showSuggetions))
                            .addComponent(cbox_fname))
                        .addGap(18, 18, 18)
                        .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_searchLayout.createSequentialGroup()
                                .addComponent(btn_editSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_editSelected1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_searchLayout.createSequentialGroup()
                                .addComponent(btn_searchInSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_showAll, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_searchLayout.setVerticalGroup(
            panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_searchBox)
                    .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_searchInSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_showAll, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_editSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_editSelected1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_searchLayout.createSequentialGroup()
                        .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbox_lecturerId)
                                .addComponent(cbox_nic))
                            .addComponent(cbox_showSuggetions))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbox_fname)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(" Search", panel_search);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_imageMouseClicked
        try {
            JFileChooser jf = new JFileChooser("C:/Users/ASUS/Desktop/aruna_edu/student_images");
            int showOpenDialog = jf.showOpenDialog(this);
            if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
                File selectedFile = jf.getSelectedFile();
                String absolutePath = selectedFile.getAbsolutePath();
                replacepath = absolutePath.replace("\\", "/");
                File file = new File(replacepath);
                Image img = ImageIO.read(file);
                img = img.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
                lbl_image.setIcon(new ImageIcon(img));

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lbl_imageMouseClicked

    private void lbl_imageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_imageMouseEntered
        panel_image.setBackground(new java.awt.Color(218, 243, 250));
    }//GEN-LAST:event_lbl_imageMouseEntered

    private void lbl_imageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_imageMouseExited
        panel_image.setBackground(new java.awt.Color(178, 230, 245));
    }//GEN-LAST:event_lbl_imageMouseExited

    private void txt_lectureridFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lectureridFocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_lectureridFocusGained

    private void txt_lectureridFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lectureridFocusLost
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_lectureridFocusLost

    private void txt_fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fnameFocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_fnameFocusGained

    private void txt_fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_fnameFocusLost
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_fnameFocusLost

    private void txt_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fnameActionPerformed
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_fnameActionPerformed

    private void txt_lnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lnameFocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_lnameFocusGained

    private void txt_lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_lnameFocusLost
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_lnameFocusLost

    private void txt_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lnameActionPerformed
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_lnameActionPerformed

    private void txt_nicFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nicFocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_nicFocusGained

    private void txt_nicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nicFocusLost
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_nicFocusLost

    private void txt_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nicActionPerformed
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_nicActionPerformed

    private void txt_cno1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cno1FocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_cno1FocusGained

    private void txt_cno1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cno1FocusLost
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_cno1FocusLost

    private void txt_cno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cno1ActionPerformed
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_cno1ActionPerformed

    private void txt_cno2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cno2FocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_cno2FocusGained

    private void txt_cno2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cno2FocusLost
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_cno2FocusLost

    private void txt_cno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cno2ActionPerformed
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_cno2ActionPerformed

    private void txt_addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_addressFocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_addressFocusGained

    private void txt_addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_addressFocusLost
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_addressFocusLost

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void txt_searchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchBoxKeyReleased
        if (cbox_showSuggetions.isSelected()) {
            removeAllRows();
            if (cbox_fname.isSelected()) {
                try {

                    for (int j = 0; j < mylist.size(); j++) {
                        int s = txt_searchBox.getText().length();
                        if (mylist.get(j).substring(0, s).equals(txt_searchBox.getText())) {

                            SEARCH("lecturer", "id_lecturer", id.get(j));
                            fillTableProcess();
                        }
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }

            } else if (cbox_nic.isSelected()) {
                System.out.println("Im in nic");
                try {
                    LIKESEARCH("lecturer", "nic", txt_searchBox.getText());
                    fillTableProcess();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else if (cbox_lecturerId.isSelected()) {
                try {
                    LIKESEARCH("lecturer", "id_lecturer", txt_searchBox.getText());
                    fillTableProcess();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_txt_searchBoxKeyReleased

    private void cbox_lecturerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_lecturerIdActionPerformed

    }//GEN-LAST:event_cbox_lecturerIdActionPerformed

    private void cbox_showSuggetionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_showSuggetionsActionPerformed
        nameSearchCboxProcess();
    }//GEN-LAST:event_cbox_showSuggetionsActionPerformed

    private void cbox_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_fnameActionPerformed
        nameSearchCboxProcess();
    }//GEN-LAST:event_cbox_fnameActionPerformed

    private void btn_searchInSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchInSearchMouseClicked

        removeAllRows();
        if (cbox_lecturerId.isSelected()) {
            try {
                SEARCH("lecturer", "id_lecturer", txt_searchBox.getText());
                ResultSet rs = getResult();
                if (rs.next()) {

                    String id_lecturer = rs.getString("id_lecturer");
                    String fname = rs.getString("fname");
                    String lname = rs.getString("lname");
                    String nic = rs.getString("nic");
                    String dob = rs.getString("dob");
                    String contact_no1 = rs.getString("contact_no1");
                    String contact_no2 = rs.getString("contact_no2");
                    String address = rs.getString("address");
                    String email = rs.getString("email");
                    String gender = rs.getString("gender");
                    
                    

                    boolean status = rs.getBoolean("status");

                    Vector v = new Vector();

                    v.add(id_lecturer);
                    v.add(fname);
                    v.add(lname);
                    v.add(nic);
                    v.add(dob);
                    v.add(contact_no1);
                    v.add(contact_no2);
                    v.add(address);
                    v.add(email);
                    v.add(gender);  

                    if (status) {
                        v.add("Active");
                    } else {
                        v.add("Inactive");
                    }

                    dtm1 = (DefaultTableModel) Table_1.getModel();
                    dtm1.addRow(v);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (cbox_nic.isSelected()) {
            try {
                SEARCH("lecturer", "nic", txt_searchBox.getText());
                ResultSet rs = getResult();
                while (rs.next()) {

                    String id_lecturer = rs.getString("id_lecturer");
                    String fname = rs.getString("fname");
                    String lname = rs.getString("lname");
                    String nic = rs.getString("nic");
                    String contact_no = rs.getString("contact_no");
                    String address = rs.getString("address");
                    String email = rs.getString("email");
                    String gender = rs.getString("gender");
                    String dob = rs.getString("dob");
                    String father_fname = rs.getString("father_fname");
                    String father_lname = rs.getString("father_lname");
                    String father_ctn = rs.getString("father_ctn");
                    String mother_fname = rs.getString("mother_fname");
                    String mother_lname = rs.getString("mother_lname");
                    String mother_ctn = rs.getString("mother_ctn");
                    String guardian_fname = rs.getString("guardian_fname");
                    String guardian_lname = rs.getString("guardian_lname");
                    String guardian_ctn = rs.getString("guardian_ctn");

                    boolean status = rs.getBoolean("status");

                    Vector v = new Vector();

                    v.add(id_lecturer);
                    v.add(fname);
                    v.add(lname);
                    v.add(nic);
                    v.add(contact_no);
                    v.add(address);
                    v.add(email);
                    v.add(gender);
                    v.add(dob);
                    v.add(father_fname);
                    v.add(father_lname);
                    v.add(father_ctn);
                    v.add(mother_fname);
                    v.add(mother_lname);
                    v.add(mother_ctn);
                    v.add(guardian_fname);
                    v.add(guardian_lname);
                    v.add(guardian_ctn);

                    if (status) {
                        v.add("Active");
                    } else {
                        v.add("Inactive");
                    }

                    dtm1 = (DefaultTableModel) Table_1.getModel();
                    dtm1.addRow(v);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (cbox_fname.isSelected()) {
            try {
                SEARCH("lecturer", "fname", txt_searchBox.getText());
                ResultSet rs = getResult();
                while (rs.next()) {

                    String id_lecturer = rs.getString("id_lecturer");
                    String fname = rs.getString("fname");
                    String lname = rs.getString("lname");
                    String nic = rs.getString("nic");
                    String contact_no = rs.getString("contact_no");
                    String address = rs.getString("address");
                    String email = rs.getString("email");
                    String gender = rs.getString("gender");
                    String dob = rs.getString("dob");
                    String father_fname = rs.getString("father_fname");
                    String father_lname = rs.getString("father_lname");
                    String father_ctn = rs.getString("father_ctn");
                    String mother_fname = rs.getString("mother_fname");
                    String mother_lname = rs.getString("mother_lname");
                    String mother_ctn = rs.getString("mother_ctn");
                    String guardian_fname = rs.getString("guardian_fname");
                    String guardian_lname = rs.getString("guardian_lname");
                    String guardian_ctn = rs.getString("guardian_ctn");

                    boolean status = rs.getBoolean("status");

                    Vector v = new Vector();

                    v.add(id_lecturer);
                    v.add(fname);
                    v.add(lname);
                    v.add(nic);
                    v.add(contact_no);
                    v.add(address);
                    v.add(email);
                    v.add(gender);
                    v.add(dob);
                    v.add(father_fname);
                    v.add(father_lname);
                    v.add(father_ctn);
                    v.add(mother_fname);
                    v.add(mother_lname);
                    v.add(mother_ctn);
                    v.add(guardian_fname);
                    v.add(guardian_lname);
                    v.add(guardian_ctn);

                    if (status) {
                        v.add("Active");
                    } else {
                        v.add("Inactive");
                    }

                    dtm1 = (DefaultTableModel) Table_1.getModel();
                    dtm1.addRow(v);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btn_searchInSearchMouseClicked

    private void btn_searchInSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchInSearchMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_searchInSearchMouseEntered

    private void btn_searchInSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchInSearchMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_searchInSearchMouseExited

    private void btn_editSelectedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelectedMouseClicked
        txt_lecturerid.setText((String) Table_1.getValueAt(Table_1.getSelectedRow(), 0));
        try {
            SEARCH("lecturer", "id_lecturer", (String) Table_1.getValueAt(Table_1.getSelectedRow(), 0));
            ResultSet rs = getResult();

            if (rs.next()) {
                txt_fname.setText(rs.getString("fname"));
                txt_lname.setText(rs.getString("lname"));
                txt_nic.setText(rs.getString("nic"));
                txt_cno1.setText(rs.getString("contact_no1"));
                txt_cno2.setText(rs.getString("contact_no2"));
                txt_address.setText(rs.getString("address"));
                txt_email.setText(rs.getString("email"));
                
                if (rs.getBoolean("status")) {
                    rad_active.setSelected(true);
                } else {
                    rad_inactive.setSelected(true);
                }
                if (rs.getString("gender").equals("Male")) {
                    jComboBox_gender.setSelectedIndex(0);
                } else if (rs.getString("gender").equals("Female")) {
                    jComboBox_gender.setSelectedIndex(1);
                } else {
                    jComboBox_gender.setSelectedIndex(2);
                }
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String text = rs.getString("dob");
                Date parse = sdf.parse(text);
                jDateChooser_dob.setDate(parse);

                replacepath = rs.getString("imagepath");
                File file = new File(replacepath);
                Image image = ImageIO.read(file);
                image = image.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
                lbl_image.setIcon(new ImageIcon(image));

                jTabbedPane1.setSelectedIndex(0);

                for (int i = 0; i < jf.size(); i++) {
                    textFieldTextType(0, jf.get(i));
                    if (jf.get(i).getText().equals("")) {
                        jf.get(i).setBackground(new java.awt.Color(253, 237, 237));
                    } else {
                        jf.get(i).setBackground(new java.awt.Color(178, 230, 245));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_editSelectedMouseClicked

    private void btn_editSelectedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelectedMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_editSelectedMouseEntered

    private void btn_editSelectedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelectedMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_editSelectedMouseExited

    private void btn_editSelected1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelected1MouseClicked
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btn_editSelected1MouseClicked

    private void btn_editSelected1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelected1MouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_editSelected1MouseEntered

    private void btn_editSelected1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelected1MouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_editSelected1MouseExited

    private void btn_showAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showAllMouseClicked
        removeAllRows();
        fillTable();
    }//GEN-LAST:event_btn_showAllMouseClicked

    private void btn_showAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showAllMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_showAllMouseEntered

    private void btn_showAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showAllMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_showAllMouseExited

    private void btn_resetMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMainMouseClicked
        clearFields();
    }//GEN-LAST:event_btn_resetMainMouseClicked

    private void btn_resetMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMainMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_resetMainMouseEntered

    private void btn_resetMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMainMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_resetMainMouseExited

    private void btn_goToSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_goToSearchMouseClicked
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btn_goToSearchMouseClicked

    private void btn_goToSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_goToSearchMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_goToSearchMouseEntered

    private void btn_goToSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_goToSearchMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_goToSearchMouseExited

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
        if(checkDependingTables()){
            int option = JOptionPane.showConfirmDialog(this, "Contract/s fround assign to the Lecturer ID, Do you want to Inactive them !");
            if(option == 0){
                try {
            UPDATE("lecturer", "status='0'", "id_lecturer", txt_lecturerid.getText());
            JOptionPane.showMessageDialog(this, "Marked as Inactive !");
            rad_inactive.setSelected(true);
            markInactive();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
            }else{
                JOptionPane.showMessageDialog(this, "Not marked as Inactive !");
            }
        }else{
            try {
            UPDATE("lecturer", "status='0'", "id_lecturer", txt_lecturerid.getText());
            JOptionPane.showMessageDialog(this, "Marked as Inactive !");
            rad_inactive.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        }
        
        
    }//GEN-LAST:event_btn_deleteMouseClicked

    private void btn_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_deleteMouseEntered

    private void btn_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_deleteMouseExited

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked

        int status = (rad_active.isSelected()) ? 1 : 0;

        try {
            Date date = jDateChooser_dob.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            dob = sdf.format(date);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Select the Birth Day !");
        }
        String gender = (String) jComboBox_gender.getSelectedItem();
       
        if (replacepath != null && !replacepath.trim().equals("")) {
            if (checkFields() && dob != null) {
                try {
                    UPDATE("lecturer",
                            "fname='" + txt_fname.getText()
                            + "',lname='" + txt_lname.getText()
                            + "',nic='" + txt_nic.getText()
                            + "',contact_no1='" + txt_cno1.getText()
                            + "',contact_no2='" + txt_cno2.getText()
                            + "',address='" + txt_address.getText()
                            + "',email='" + txt_email.getText()
                            + "',gender='" + gender
                            + "',dob='" + dob
                            + "',imagepath='" + replacepath
                            + "',status='" + status
                            + "'", "id_lecturer",
                            txt_lecturerid.getText());
                    JOptionPane.showMessageDialog(this, " Updated !");

                } catch (SQLIntegrityConstraintViolationException ex) {
                    JOptionPane.showMessageDialog(this, "Lecturer ID or NIC Number has already in the DataBase !. The Error Message: " + ex.getMessage());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Fill all Fields !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please add a profile picture !");
        }
    }//GEN-LAST:event_btn_updateMouseClicked

    private void btn_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_updateMouseEntered

    private void btn_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_updateMouseExited

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
if(isValid(txt_email.getText())){
        int status = (rad_active.isSelected()) ? 1 : 0;

        try {
            Date date = jDateChooser_dob.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            dob = sdf.format(date);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Select the Birth Day !");
        }
        String gender = (String) jComboBox_gender.getSelectedItem();
        
        
        if (replacepath != null && !replacepath.trim().equals("")) {
            if (checkFields() && dob != null) {
                try {
                    SAVE("lecturer", "'"+
                            txt_lecturerid.getText()+"','"+
                            txt_fname.getText()+"','"+
                            txt_lname.getText()+"','"+
                            txt_nic.getText()+"','"+
                            dob+"','"+
                            txt_cno1.getText()+"','"+
                            txt_cno2.getText()+"','"+
                            txt_address.getText()+"','"+
                            txt_email.getText()+"','"+
                            gender+"','"+
                            status+"','"+
                            replacepath+"'");
                    JOptionPane.showMessageDialog(this, " Saved !");
                    clearFields();
                    txt_fname.grabFocus();

                } catch (SQLIntegrityConstraintViolationException ex) {
                    JOptionPane.showMessageDialog(this, "Lecturer ID or NIC Number has already in the DataBase !. The Error Message: " + ex.getMessage());
                } catch (Exception e) {
//                    
e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Fill all Fields !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please add a profile picture !");
        }
        }else{
           JOptionPane.showMessageDialog(this, "Enter a correct Email !!");
       }
    }//GEN-LAST:event_btn_saveMouseClicked

    private void btn_saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_saveMouseEntered

    private void btn_saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_saveMouseExited

    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_emailFocusGained

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
         warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_emailFocusLost

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_1;
    private javax.swing.JLabel btn_delete;
    private javax.swing.JLabel btn_editSelected;
    private javax.swing.JLabel btn_editSelected1;
    private javax.swing.JLabel btn_goToSearch;
    private javax.swing.JLabel btn_resetMain;
    private javax.swing.JLabel btn_save;
    private javax.swing.JLabel btn_searchInSearch;
    private javax.swing.JLabel btn_showAll;
    private javax.swing.JLabel btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbox_fname;
    private javax.swing.JCheckBox cbox_lecturerId;
    private javax.swing.JCheckBox cbox_nic;
    private javax.swing.JCheckBox cbox_showSuggetions;
    private javax.swing.JComboBox<String> jComboBox_gender;
    private com.toedter.calendar.JDateChooser jDateChooser_dob;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JPanel panel_image;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_search;
    private javax.swing.JRadioButton rad_active;
    private javax.swing.JRadioButton rad_inactive;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_cno1;
    private javax.swing.JTextField txt_cno2;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fname;
    private javax.swing.JTextField txt_lecturerid;
    private javax.swing.JTextField txt_lname;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_searchBox;
    // End of variables declaration//GEN-END:variables

    private void warnningLabel(int id, JTextField jTextField) {

        if (id == 1004) {
            if (jTextField.getFont().getSize() == 14) {
                prevText = jTextField.getText();
                jTextField.setText("");
                textFieldTextType(0, jTextField);

            }
            jTextField.setBackground(new java.awt.Color(218, 243, 250));
        } else if (id == 1005) {
            if (jTextField.getText().equals("")) {
                jTextField.setText(prevText);
                textFieldTextType(1, jTextField);
                prevText = null;
                jTextField.setBackground(new java.awt.Color(253, 237, 237));

            } else {
                prevText = null;
                jTextField.setBackground(new java.awt.Color(178, 230, 245));
            }
        }

    }

    private void textFieldTextType(int i, JTextField jt) {
        if (i == 0) {
            jt.setForeground(new java.awt.Color(0, 0, 0));
            Font f = new Font("Tahoma", 0, 16);
            jt.setFont(f);
        } else if (i == 1) {
            jt.setForeground(new java.awt.Color(124, 124, 124));
            Font f = new Font("Tahoma", 0, 14);
            jt.setFont(f);
        }

    }

    private void setDefaultTextField() {
        for (JTextField jTextField : jf) {
            jTextField.setBackground(new java.awt.Color(253, 237, 237));
            jTextField.setForeground(new java.awt.Color(124, 124, 124));
            Font f = new Font("Tahoma", 0, 14);
            jTextField.setFont(f);
        }
    }

    private void addTextFieldsToList() {
        jf = new ArrayList<JTextField>();
        jf.add(txt_fname);
        jf.add(txt_lname);
        jf.add(txt_nic);
        jf.add(txt_cno1);
        jf.add(txt_cno2);
        jf.add(txt_address);
        jf.add(txt_email);

    }

    private void addDefaultTextToList() {
        defaultText = new ArrayList<String>();
        defaultText.add("First name");
        defaultText.add("Last name");
        defaultText.add("NIC");
        defaultText.add("Contact number 1.");
        defaultText.add("Contact number 2.");
        defaultText.add("Address");
        defaultText.add("Email");

    }

    private void setDefaultText() {
        for (int i = 0; i < defaultText.size(); i++) {
            jf.get(i).setText(defaultText.get(i));
        }
    }

    private boolean checkFields() {

        if (txt_lecturerid.getText().equals("")
                && txt_fname.getText().equals("")
                && txt_lname.getText().equals("")
                && txt_nic.getText().equals("")
                && txt_cno1.getText().equals("")
                && txt_address.getText().equals("")) {
            return false;
        } else {
            return true;
        }

    }

    private void clearFields() {
        generateLecturerId();
        setDefaultText();
        setDefaultTextField();
        rad_active.setSelected(true);
        jDateChooser_dob.setDate(null);
        replacepath = null;
        lbl_image.setIcon(icn4);
    }
    
     private void nameSearchCboxProcess() {
        if (cbox_showSuggetions.isSelected() && cbox_fname.isSelected()) {
            removeAllRows();
            try {
                clearArrays();

                PVTSEARCH2();

                ResultSet rs1 = getResult();
                mylist = new ArrayList<String>();
                id = new ArrayList<String>();
                while (rs1.next()) {
                    mylist.add(rs1.getString("cname"));
                    id.add(rs1.getString("id_lecturer"));
                }
            } catch (Exception e) {
                
                e.printStackTrace();
            }
        }
    }
     private void removeAllRows() {
        for (int i = Table_1.getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) Table_1.getModel()).removeRow(i);
        }
    }
     private void clearArrays() {
        try {
            mylist.clear();
            id.clear();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
     
     private void fillTable() {
        try {
            SEARCH("lecturer");
            fillTableProcess();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     private void fillTableProcess() {
         
         try {
             
            ResultSet rs = getResult();
            while (rs.next()) {
                
                String id_lecturer = rs.getString("id_lecturer");
                String fname = rs.getString("fname");
                String lname = rs.getString("lname");
                String nic = rs.getString("nic");
                String dob = rs.getString("dob");
                String contact_no1 = rs.getString("contact_no1");
                String contact_no2 = rs.getString("contact_no2");
                String address = rs.getString("address");
                String email = rs.getString("email");
                String gender = rs.getString("gender");
                boolean status = rs.getBoolean("status");

                Vector v = new Vector();

                v.add(id_lecturer);
                v.add(fname);
                v.add(lname);
                v.add(nic);
                v.add(dob);
                v.add(contact_no1);
                v.add(contact_no2);
                v.add(address);
                v.add(email);
                v.add(gender);
                if (status) {
                    v.add("Active");
                } else {
                    v.add("Inactive");
                }

                dtm1 = (DefaultTableModel) Table_1.getModel();
                dtm1.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     private void colorButtons(int i, JLabel jl) {
        if (i == 504) {
            jl.setBackground(new java.awt.Color(117, 170, 179));

        } else if (i == 505) {
            jl.setBackground(new java.awt.Color(69, 141, 152));
        }
    }

    private void generateLecturerId() {
        try {
            ResultSet rs = DB.search("select count(*) as inv_count from lecturer");
            if (rs.next()) {
                int count = rs.getInt("inv_count");
                String invoiceid = "AELCTR" + (++count);
                txt_lecturerid.setText(invoiceid);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public static  boolean isValid(String email)
    {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+
                            "[a-zA-Z0-9_+&*-]+)*@" +
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" +
                            "A-Z]{2,7}$";
                              
        Pattern pat = Pattern.compile(emailRegex);
        if (email == null)
            return false;
        return pat.matcher(email).matches();
    }
    
    private boolean checkDependingTables(){
        boolean found=true;
        try {
            ResultSet rs = DB.search("select count(id_contract) as rowCount from lecturer_contract where id_lecturer='"+txt_lecturerid.getText()+"'");
            rs.next();
            int rowCount = rs.getInt("rowCount");
            
            if(rowCount==0){
                found = false;
            }else{
                found = true;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return found;
    }
    
    private void markInactive(){
        try {
            ResultSet rs = DB.search("select id_contract from lecturer_contract where id_lecturer='"+txt_lecturerid.getText()+"'");
            
            while (rs.next()) {        
                String id_contract = rs.getString("id_contract");
                DB.push("update lecturer_contract set status='0' where id_contract='"+id_contract+"'");
                }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

}
