package com.arunaedu.main;

import com.anuraedu.common.SQ;
import static com.anuraedu.common.SQ.STATUSSEARCH;
import static com.anuraedu.common.SystemConfigData.getEmployee;
import static com.anuraedu.common.SystemConfigData.getUserType;
import com.anuraedu.db.DB;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Main extends javax.swing.JFrame {

    //Student section activeInterFrame = 1;
    //Student section activeInterFrame = 2;
    private int activeInterFrame;

    Object iframe;
    int menuLabel;
    SimpleDateFormat sdf1;
    Date date;

    int lastIndex = 9;
    int firstIndex = 0;
    ArrayList<String> topic = new ArrayList<String>();

    public Main() {
        initComponents();
        panel_def.setVisible(false);
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
        sdf1 = new SimpleDateFormat(lbl_date.getText());
        setDateAndTime();
        updateJlabels();
        calculateTodayQuary();
        calculateStudentAmount();
        calculateTotalLecturers();
        calculateRunningContracts();
        checkPermission();
        setUserDetails();
        addNotes();
        setTopics();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        panel_menu = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_dashboard = new javax.swing.JLabel();
        lbl_acdmanage = new javax.swing.JLabel();
        lbl_student = new javax.swing.JLabel();
        lbl_lecturer = new javax.swing.JLabel();
        lbl_system = new javax.swing.JLabel();
        panel_head = new javax.swing.JPanel();
        lbl_date = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_minimize = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        lbl_logout1 = new javax.swing.JLabel();
        lbl_userType = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        desktoppane_1 = new javax.swing.JDesktopPane();
        panel_dashboard = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel25 = new javax.swing.JLabel();
        lbl_studentAmount = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        lbl_lecturerAmount = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        lbl_contractAmount = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_topic = new javax.swing.JTextField();
        txt_note = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lbl_n1 = new javax.swing.JLabel();
        lbl_n2 = new javax.swing.JLabel();
        lbl_n3 = new javax.swing.JLabel();
        lbl_n4 = new javax.swing.JLabel();
        lbl_n5 = new javax.swing.JLabel();
        lbl_n6 = new javax.swing.JLabel();
        lbl_n7 = new javax.swing.JLabel();
        lbl_n8 = new javax.swing.JLabel();
        lbl_n9 = new javax.swing.JLabel();
        lbl_n10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jButton10 = new javax.swing.JButton();
        panel_def = new javax.swing.JPanel();
        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();
        lbl_4 = new javax.swing.JLabel();
        lbl_5 = new javax.swing.JLabel();
        lbl_6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_menu.setkEndColor(new java.awt.Color(0, 0, 70));
        panel_menu.setkStartColor(new java.awt.Color(28, 181, 224));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/arunaedu/main/output-onlinepngtools.png"))); // NOI18N

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(6, 1));

        lbl_dashboard.setBackground(new java.awt.Color(157, 223, 242));
        lbl_dashboard.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        lbl_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dashboard.setText("Dashboard");
        lbl_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseReleased(evt);
            }
        });
        jPanel6.add(lbl_dashboard);

        lbl_acdmanage.setBackground(new java.awt.Color(157, 223, 242));
        lbl_acdmanage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_acdmanage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_acdmanage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_acdmanage.setText("ACD Manage");
        lbl_acdmanage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_acdmanageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_acdmanageMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_acdmanageMouseReleased(evt);
            }
        });
        jPanel6.add(lbl_acdmanage);

        lbl_student.setBackground(new java.awt.Color(157, 223, 242));
        lbl_student.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_student.setForeground(new java.awt.Color(255, 255, 255));
        lbl_student.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_student.setText("Student");
        lbl_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_studentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_studentMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_studentMouseReleased(evt);
            }
        });
        jPanel6.add(lbl_student);

        lbl_lecturer.setBackground(new java.awt.Color(157, 223, 242));
        lbl_lecturer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_lecturer.setForeground(new java.awt.Color(255, 255, 255));
        lbl_lecturer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_lecturer.setText("Lecturer");
        lbl_lecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_lecturerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_lecturerMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_lecturerMouseReleased(evt);
            }
        });
        jPanel6.add(lbl_lecturer);

        lbl_system.setBackground(new java.awt.Color(157, 223, 242));
        lbl_system.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_system.setForeground(new java.awt.Color(255, 255, 255));
        lbl_system.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_system.setText("System");
        lbl_system.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_systemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_systemMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_systemMouseReleased(evt);
            }
        });
        jPanel6.add(lbl_system);

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 336, Short.MAX_VALUE))
        );

        kGradientPanel1.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1080));

        panel_head.setBackground(new java.awt.Color(76, 76, 76));
        panel_head.setToolTipText("");

        lbl_date.setBackground(new java.awt.Color(255, 255, 255));
        lbl_date.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(255, 255, 255));
        lbl_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_date.setText("YYYY-MM-dd HH:mm:ss");

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 1, 1));

        lbl_minimize.setBackground(new java.awt.Color(178, 230, 245));
        lbl_minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_minimize.setForeground(new java.awt.Color(255, 255, 255));
        lbl_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_minimize.setText("-");
        lbl_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_minimizeMouseExited(evt);
            }
        });
        jPanel1.add(lbl_minimize);

        lbl_close.setBackground(new java.awt.Color(226, 62, 47));
        lbl_close.setFont(new java.awt.Font("Gabriola", 0, 20)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_closeMouseExited(evt);
            }
        });
        jPanel1.add(lbl_close);

        lbl_logout1.setBackground(new java.awt.Color(178, 230, 245));
        lbl_logout1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_logout1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_logout1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_logout1MouseExited(evt);
            }
        });

        lbl_userType.setBackground(new java.awt.Color(255, 255, 255));
        lbl_userType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_userType.setForeground(new java.awt.Color(255, 255, 255));
        lbl_userType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_userType.setText("User Type : xxxxx");

        lbl_user.setBackground(new java.awt.Color(255, 255, 255));
        lbl_user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(255, 255, 255));
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setText("System User : xxxxx");

        javax.swing.GroupLayout panel_headLayout = new javax.swing.GroupLayout(panel_head);
        panel_head.setLayout(panel_headLayout);
        panel_headLayout.setHorizontalGroup(
            panel_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_headLayout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(lbl_userType, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328)
                .addComponent(lbl_logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(292, 292, 292)
                .addComponent(lbl_date, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
            .addGroup(panel_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_headLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1377, Short.MAX_VALUE)))
        );
        panel_headLayout.setVerticalGroup(
            panel_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(lbl_logout1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_userType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_headLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_user, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        kGradientPanel1.add(panel_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1670, 40));

        panel_dashboard.setBackground(new java.awt.Color(242, 242, 242));
        panel_dashboard.setForeground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(242, 242, 242));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0, 20, 20));

        kGradientPanel2.setkEndColor(new java.awt.Color(180, 241, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(105, 226, 255));

        jLabel13.setBackground(new java.awt.Color(20, 125, 177));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" Today Collection (Class fees)");
        jLabel13.setOpaque(true);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(76, 76, 76));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Total (Rs)");

        lbl_total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_total.setForeground(new java.awt.Color(76, 76, 76));
        lbl_total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_total.setText("00.00");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_total, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel10.add(kGradientPanel2);

        kGradientPanel5.setkEndColor(new java.awt.Color(180, 241, 255));
        kGradientPanel5.setkStartColor(new java.awt.Color(105, 226, 255));

        jLabel25.setBackground(new java.awt.Color(20, 125, 177));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(" Total Students Amount");
        jLabel25.setOpaque(true);

        lbl_studentAmount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_studentAmount.setForeground(new java.awt.Color(76, 76, 76));
        lbl_studentAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_studentAmount.setText("0");

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(lbl_studentAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_studentAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        jPanel10.add(kGradientPanel5);

        kGradientPanel4.setkEndColor(new java.awt.Color(180, 241, 255));
        kGradientPanel4.setkStartColor(new java.awt.Color(105, 226, 255));

        lbl_lecturerAmount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_lecturerAmount.setForeground(new java.awt.Color(76, 76, 76));
        lbl_lecturerAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_lecturerAmount.setText("0");

        jLabel26.setBackground(new java.awt.Color(20, 125, 177));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText(" Total LectureRs Amount");
        jLabel26.setOpaque(true);

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(lbl_lecturerAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_lecturerAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        jPanel10.add(kGradientPanel4);

        kGradientPanel3.setkEndColor(new java.awt.Color(180, 241, 255));
        kGradientPanel3.setkStartColor(new java.awt.Color(105, 226, 255));

        lbl_contractAmount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_contractAmount.setForeground(new java.awt.Color(76, 76, 76));
        lbl_contractAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_contractAmount.setText("0");

        jLabel30.setBackground(new java.awt.Color(20, 125, 177));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText(" Runnig Contracts");
        jLabel30.setOpaque(true);

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
            .addComponent(lbl_contractAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_contractAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        jPanel10.add(kGradientPanel3);

        jPanel4.setBackground(new java.awt.Color(20, 125, 177));
        jPanel4.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel4MouseWheelMoved(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(40, 153, 198));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MANAGE NOTE");

        jButton8.setBackground(new java.awt.Color(20, 125, 177));
        jButton8.setText("SAVE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(20, 125, 177));
        jButton9.setText("DELETE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Topic");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Note");

        jPanel2.setBackground(new java.awt.Color(111, 187, 217));

        jButton11.setBackground(new java.awt.Color(111, 187, 217));
        jButton11.setText("Student Remaining Payments");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_topic)
                    .addComponent(txt_note)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_topic, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_note, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOTES TOPICS");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("UP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("DOWN");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        lbl_n1.setBackground(new java.awt.Color(111, 187, 217));
        lbl_n1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_n1.setText("Empty");
        lbl_n1.setOpaque(true);
        lbl_n1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_n1MouseClicked(evt);
            }
        });

        lbl_n2.setBackground(new java.awt.Color(111, 187, 217));
        lbl_n2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_n2.setText("Empty");
        lbl_n2.setOpaque(true);
        lbl_n2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_n2MouseClicked(evt);
            }
        });

        lbl_n3.setBackground(new java.awt.Color(111, 187, 217));
        lbl_n3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_n3.setText("Empty");
        lbl_n3.setOpaque(true);
        lbl_n3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_n3MouseClicked(evt);
            }
        });

        lbl_n4.setBackground(new java.awt.Color(111, 187, 217));
        lbl_n4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_n4.setText("Empty");
        lbl_n4.setOpaque(true);
        lbl_n4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_n4MouseClicked(evt);
            }
        });

        lbl_n5.setBackground(new java.awt.Color(111, 187, 217));
        lbl_n5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_n5.setText("Empty");
        lbl_n5.setOpaque(true);
        lbl_n5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_n5MouseClicked(evt);
            }
        });

        lbl_n6.setBackground(new java.awt.Color(111, 187, 217));
        lbl_n6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_n6.setText("Empty");
        lbl_n6.setOpaque(true);
        lbl_n6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_n6MouseClicked(evt);
            }
        });

        lbl_n7.setBackground(new java.awt.Color(111, 187, 217));
        lbl_n7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_n7.setText("Empty");
        lbl_n7.setOpaque(true);
        lbl_n7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_n7MouseClicked(evt);
            }
        });

        lbl_n8.setBackground(new java.awt.Color(111, 187, 217));
        lbl_n8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_n8.setText("Empty");
        lbl_n8.setOpaque(true);
        lbl_n8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_n8MouseClicked(evt);
            }
        });

        lbl_n9.setBackground(new java.awt.Color(111, 187, 217));
        lbl_n9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_n9.setText("Empty");
        lbl_n9.setOpaque(true);
        lbl_n9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_n9MouseClicked(evt);
            }
        });

        lbl_n10.setBackground(new java.awt.Color(111, 187, 217));
        lbl_n10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_n10.setText("Empty");
        lbl_n10.setOpaque(true);
        lbl_n10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_n10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_n5, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_n6, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_n10, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_n1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_n2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_n3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_n4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_n5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_n6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_n7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_n8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_n9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_n10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jButton1.setBackground(new java.awt.Color(20, 125, 177));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("STUDENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(20, 125, 177));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LECTURER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(20, 125, 177));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("STUDENT PAYMENTS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(20, 125, 177));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("LECTURER PAYMENTS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(20, 125, 177));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("LOGOUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(20, 125, 177));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("ADD DATE COMPLETED CLASSES");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_dashboardLayout = new javax.swing.GroupLayout(panel_dashboard);
        panel_dashboard.setLayout(panel_dashboardLayout);
        panel_dashboardLayout.setHorizontalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 1598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_dashboardLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panel_dashboardLayout.setVerticalGroup(
            panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dashboardLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panel_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        panel_def.setBackground(new java.awt.Color(242, 242, 242));

        lbl_1.setBackground(new java.awt.Color(20, 125, 177));
        lbl_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_1.setOpaque(true);
        lbl_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_1MouseReleased(evt);
            }
        });

        lbl_2.setBackground(new java.awt.Color(20, 125, 177));
        lbl_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_2.setOpaque(true);
        lbl_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_2MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_2MouseReleased(evt);
            }
        });

        lbl_3.setBackground(new java.awt.Color(20, 125, 177));
        lbl_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_3.setOpaque(true);
        lbl_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_3MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_3MouseReleased(evt);
            }
        });

        lbl_4.setBackground(new java.awt.Color(20, 125, 177));
        lbl_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_4.setOpaque(true);
        lbl_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_4MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_4MouseReleased(evt);
            }
        });

        lbl_5.setBackground(new java.awt.Color(20, 125, 177));
        lbl_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_5.setOpaque(true);
        lbl_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_5MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_5MouseReleased(evt);
            }
        });

        lbl_6.setBackground(new java.awt.Color(20, 125, 177));
        lbl_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_6.setOpaque(true);
        lbl_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_6MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_6MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout panel_defLayout = new javax.swing.GroupLayout(panel_def);
        panel_def.setLayout(panel_defLayout);
        panel_defLayout.setHorizontalGroup(
            panel_defLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_defLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(panel_defLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_6, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_4, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_3, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1047, Short.MAX_VALUE))
        );
        panel_defLayout.setVerticalGroup(
            panel_defLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_defLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(613, Short.MAX_VALUE))
        );

        desktoppane_1.setLayer(panel_dashboard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktoppane_1.setLayer(panel_def, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktoppane_1Layout = new javax.swing.GroupLayout(desktoppane_1);
        desktoppane_1.setLayout(desktoppane_1Layout);
        desktoppane_1Layout.setHorizontalGroup(
            desktoppane_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_dashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(desktoppane_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_def, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        desktoppane_1Layout.setVerticalGroup(
            desktoppane_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(desktoppane_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_def, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kGradientPanel1.add(desktoppane_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 1670, 1040));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_logout1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logout1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_logout1MouseEntered

    private void lbl_logout1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logout1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_logout1MouseExited

    private void lbl_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseEntered
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_dashboardMouseEntered

    private void lbl_acdmanageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_acdmanageMouseEntered
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_acdmanageMouseEntered

    private void lbl_studentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_studentMouseEntered
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_studentMouseEntered

    private void lbl_lecturerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_lecturerMouseEntered
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_lecturerMouseEntered

    private void lbl_systemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_systemMouseEntered
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_systemMouseEntered

    private void lbl_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseExited
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_dashboardMouseExited

    private void lbl_acdmanageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_acdmanageMouseExited
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_acdmanageMouseExited

    private void lbl_studentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_studentMouseExited
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_studentMouseExited

    private void lbl_lecturerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_lecturerMouseExited
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_lecturerMouseExited

    private void lbl_systemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_systemMouseExited
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_systemMouseExited

    private void lbl_dashboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseReleased
        clearAllPanel();
        removeFrame();
        panel_dashboard.setVisible(true);
    }//GEN-LAST:event_lbl_dashboardMouseReleased

    private void lbl_acdmanageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_acdmanageMouseReleased
        clearAllPanel();
        removeFrame();
        menuLabel = 1;
        setLabelName();
        panel_def.setVisible(true);
    }//GEN-LAST:event_lbl_acdmanageMouseReleased

    private void lbl_studentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_studentMouseReleased
        clearAllPanel();
        removeFrame();
        menuLabel = 2;
        setLabelName();
        panel_def.setVisible(true);
    }//GEN-LAST:event_lbl_studentMouseReleased

    private void lbl_lecturerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_lecturerMouseReleased
        clearAllPanel();
        removeFrame();
        menuLabel = 3;
        setLabelName();
        panel_def.setVisible(true);
    }//GEN-LAST:event_lbl_lecturerMouseReleased

    private void lbl_systemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_systemMouseReleased
        clearAllPanel();
        removeFrame();
        menuLabel = 5;
        setLabelName();
        panel_def.setVisible(true);
    }//GEN-LAST:event_lbl_systemMouseReleased

    private void lbl_1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_1MouseReleased
        clearAllPanel();
        iframeOpen((JLabel) evt.getSource());

    }//GEN-LAST:event_lbl_1MouseReleased

    private void lbl_2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_2MouseReleased
        clearAllPanel();
        iframeOpen((JLabel) evt.getSource());
    }//GEN-LAST:event_lbl_2MouseReleased

    private void lbl_3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_3MouseReleased
        clearAllPanel();
        iframeOpen((JLabel) evt.getSource());
    }//GEN-LAST:event_lbl_3MouseReleased

    private void lbl_4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_4MouseReleased
        clearAllPanel();
        iframeOpen((JLabel) evt.getSource());
    }//GEN-LAST:event_lbl_4MouseReleased

    private void lbl_5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_5MouseReleased
        clearAllPanel();
        iframeOpen((JLabel) evt.getSource());
    }//GEN-LAST:event_lbl_5MouseReleased

    private void lbl_6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_6MouseReleased
        clearAllPanel();
        iframeOpen((JLabel) evt.getSource());
    }//GEN-LAST:event_lbl_6MouseReleased

    private void lbl_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseEntered
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_closeMouseEntered

    private void lbl_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseEntered
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_minimizeMouseEntered

    private void lbl_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseExited
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_closeMouseExited

    private void lbl_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseExited
        changeButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_minimizeMouseExited

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lbl_minimizeMouseClicked

    private void lbl_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_1MouseEntered
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_1MouseEntered

    private void lbl_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_2MouseEntered
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_2MouseEntered

    private void lbl_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_3MouseEntered
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_3MouseEntered

    private void lbl_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_4MouseEntered
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_4MouseEntered

    private void lbl_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_5MouseEntered
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_5MouseEntered

    private void lbl_6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_6MouseEntered
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_6MouseEntered

    private void lbl_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_1MouseExited
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_1MouseExited

    private void lbl_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_2MouseExited
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_2MouseExited

    private void lbl_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_3MouseExited
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_3MouseExited

    private void lbl_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_4MouseExited
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_4MouseExited

    private void lbl_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_5MouseExited
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_5MouseExited

    private void lbl_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_6MouseExited
        changeDefButtonColor((JLabel) evt.getSource(), evt.getID());
    }//GEN-LAST:event_lbl_6MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        iframe = new StudentRegistration();
        clearAllPanel();
        removeFrame();
        desktoppane_1.add((Component) iframe).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        iframe = new LecturerRegistration();
        clearAllPanel();
        removeFrame();
        desktoppane_1.add((Component) iframe).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        iframe = new LecturerPayment();
        clearAllPanel();
        removeFrame();
        desktoppane_1.add((Component) iframe).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        iframe = new StudentPayment();
        clearAllPanel();
        removeFrame();
        desktoppane_1.add((Component) iframe).setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (0 < firstIndex) {
            int i1 = lastIndex - 10;
            int i2 = lastIndex - 9;
            int i3 = lastIndex - 8;
            int i4 = lastIndex - 7;
            int i5 = lastIndex - 6;
            int i6 = lastIndex - 5;
            int i7 = lastIndex - 4;
            int i8 = lastIndex - 3;
            int i9 = lastIndex - 2;
            int i10 = lastIndex - 1;

            lbl_n1.setText(String.valueOf(topic.get(i1)));
            lbl_n2.setText(String.valueOf(topic.get(i2)));
            lbl_n3.setText(String.valueOf(topic.get(i3)));
            lbl_n4.setText(String.valueOf(topic.get(i4)));
            lbl_n5.setText(String.valueOf(topic.get(i5)));
            lbl_n6.setText(String.valueOf(topic.get(i6)));
            lbl_n7.setText(String.valueOf(topic.get(i7)));
            lbl_n8.setText(String.valueOf(topic.get(i8)));
            lbl_n9.setText(String.valueOf(topic.get(i9)));
            lbl_n10.setText(String.valueOf(topic.get(i10)));
            firstIndex = firstIndex - 1;
            lastIndex = lastIndex - 1;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (topic.size() > (lastIndex + 1)) {
            int i1 = firstIndex + 1;
            int i2 = firstIndex + 2;
            int i3 = firstIndex + 3;
            int i4 = firstIndex + 4;
            int i5 = firstIndex + 5;
            int i6 = firstIndex + 6;
            int i7 = firstIndex + 7;
            int i8 = firstIndex + 8;
            int i9 = firstIndex + 9;
            int i10 = firstIndex + 10;
            lbl_n1.setText(String.valueOf(topic.get(i1)));
            lbl_n2.setText(String.valueOf(topic.get(i2)));
            lbl_n3.setText(String.valueOf(topic.get(i3)));
            lbl_n4.setText(String.valueOf(topic.get(i4)));
            lbl_n5.setText(String.valueOf(topic.get(i5)));
            lbl_n6.setText(String.valueOf(topic.get(i6)));
            lbl_n7.setText(String.valueOf(topic.get(i7)));
            lbl_n8.setText(String.valueOf(topic.get(i8)));
            lbl_n9.setText(String.valueOf(topic.get(i9)));
            lbl_n10.setText(String.valueOf(topic.get(i10)));
            firstIndex = firstIndex + 1;
            lastIndex = lastIndex + 1;
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void lbl_n1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_n1MouseClicked
        getSelecttedNote(lbl_n1);
    }//GEN-LAST:event_lbl_n1MouseClicked

    private void lbl_n2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_n2MouseClicked
        getSelecttedNote(lbl_n2);
    }//GEN-LAST:event_lbl_n2MouseClicked

    private void lbl_n3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_n3MouseClicked
        getSelecttedNote(lbl_n3);
    }//GEN-LAST:event_lbl_n3MouseClicked

    private void lbl_n4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_n4MouseClicked
       getSelecttedNote(lbl_n4);
    }//GEN-LAST:event_lbl_n4MouseClicked

    private void lbl_n5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_n5MouseClicked
       getSelecttedNote(lbl_n5);
    }//GEN-LAST:event_lbl_n5MouseClicked

    private void lbl_n6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_n6MouseClicked
        getSelecttedNote(lbl_n6);
    }//GEN-LAST:event_lbl_n6MouseClicked

    private void lbl_n7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_n7MouseClicked
       getSelecttedNote(lbl_n7);
    }//GEN-LAST:event_lbl_n7MouseClicked

    private void lbl_n8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_n8MouseClicked
       getSelecttedNote(lbl_n8);
    }//GEN-LAST:event_lbl_n8MouseClicked

    private void lbl_n9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_n9MouseClicked
       getSelecttedNote(lbl_n9);
    }//GEN-LAST:event_lbl_n9MouseClicked

    private void lbl_n10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_n10MouseClicked
       getSelecttedNote(lbl_n10);
    }//GEN-LAST:event_lbl_n10MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            if(!txt_note.getText().equals("")&&!txt_topic.getText().equals("")){
            DB.push("insert into notes values ('"+
                    txt_topic.getText()+"','"+
                    txt_note.getText()+"')");
            JOptionPane.showMessageDialog(this, "Saved !");
                    notesReset();
            }else{
                JOptionPane.showMessageDialog(this, "Fill All Fileds !");
            }
        } catch (SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "Topic has already in the database, use a new one !");
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            if(!txt_topic.getText().equals("")){
             int jop = JOptionPane.showConfirmDialog(this, "Are you sure ?");
             if(jop == 0){
             DB.push("DELETE FROM notes WHERE topic='"+txt_topic.getText()+"'");
             notesReset();
             JOptionPane.showMessageDialog(this, "Done !");
             }
            }else{
                JOptionPane.showMessageDialog(this, "Fill Topic Fields !");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        AddDateCompletedClasses adcc = new AddDateCompletedClasses();
        adcc.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        StudentRemainingPayments srp = new StudentRemainingPayments();
        srp.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jPanel4MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel4MouseWheelMoved
        if(evt.getWheelRotation()==1){
                    if (0 < firstIndex) {
            int i1 = lastIndex - 10;
            int i2 = lastIndex - 9;
            int i3 = lastIndex - 8;
            int i4 = lastIndex - 7;
            int i5 = lastIndex - 6;
            int i6 = lastIndex - 5;
            int i7 = lastIndex - 4;
            int i8 = lastIndex - 3;
            int i9 = lastIndex - 2;
            int i10 = lastIndex - 1;

            lbl_n1.setText(String.valueOf(topic.get(i1)));
            lbl_n2.setText(String.valueOf(topic.get(i2)));
            lbl_n3.setText(String.valueOf(topic.get(i3)));
            lbl_n4.setText(String.valueOf(topic.get(i4)));
            lbl_n5.setText(String.valueOf(topic.get(i5)));
            lbl_n6.setText(String.valueOf(topic.get(i6)));
            lbl_n7.setText(String.valueOf(topic.get(i7)));
            lbl_n8.setText(String.valueOf(topic.get(i8)));
            lbl_n9.setText(String.valueOf(topic.get(i9)));
            lbl_n10.setText(String.valueOf(topic.get(i10)));
            firstIndex = firstIndex - 1;
            lastIndex = lastIndex - 1;
        }
        }else if(evt.getWheelRotation()==-1){
                    if (topic.size() > (lastIndex + 1)) {
            int i1 = firstIndex + 1;
            int i2 = firstIndex + 2;
            int i3 = firstIndex + 3;
            int i4 = firstIndex + 4;
            int i5 = firstIndex + 5;
            int i6 = firstIndex + 6;
            int i7 = firstIndex + 7;
            int i8 = firstIndex + 8;
            int i9 = firstIndex + 9;
            int i10 = firstIndex + 10;
            lbl_n1.setText(String.valueOf(topic.get(i1)));
            lbl_n2.setText(String.valueOf(topic.get(i2)));
            lbl_n3.setText(String.valueOf(topic.get(i3)));
            lbl_n4.setText(String.valueOf(topic.get(i4)));
            lbl_n5.setText(String.valueOf(topic.get(i5)));
            lbl_n6.setText(String.valueOf(topic.get(i6)));
            lbl_n7.setText(String.valueOf(topic.get(i7)));
            lbl_n8.setText(String.valueOf(topic.get(i8)));
            lbl_n9.setText(String.valueOf(topic.get(i9)));
            lbl_n10.setText(String.valueOf(topic.get(i10)));
            firstIndex = firstIndex + 1;
            lastIndex = lastIndex + 1;
        }
        }
    }//GEN-LAST:event_jPanel4MouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktoppane_1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_5;
    private javax.swing.JLabel lbl_6;
    private javax.swing.JLabel lbl_acdmanage;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_contractAmount;
    private javax.swing.JLabel lbl_dashboard;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_lecturer;
    private javax.swing.JLabel lbl_lecturerAmount;
    private javax.swing.JLabel lbl_logout1;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JLabel lbl_n1;
    private javax.swing.JLabel lbl_n10;
    private javax.swing.JLabel lbl_n2;
    private javax.swing.JLabel lbl_n3;
    private javax.swing.JLabel lbl_n4;
    private javax.swing.JLabel lbl_n5;
    private javax.swing.JLabel lbl_n6;
    private javax.swing.JLabel lbl_n7;
    private javax.swing.JLabel lbl_n8;
    private javax.swing.JLabel lbl_n9;
    private javax.swing.JLabel lbl_student;
    private javax.swing.JLabel lbl_studentAmount;
    private javax.swing.JLabel lbl_system;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_userType;
    private javax.swing.JPanel panel_dashboard;
    private javax.swing.JPanel panel_def;
    private javax.swing.JPanel panel_head;
    private keeptoo.KGradientPanel panel_menu;
    private javax.swing.JTextField txt_note;
    private javax.swing.JTextField txt_topic;
    // End of variables declaration//GEN-END:variables

    private void changeButtonColor(JLabel jl, int evnt) {

        if (evnt == 504) {
            jl.setOpaque(true);
            jl.revalidate();
            jl.repaint();
        } else if (evnt == 505) {
            jl.setOpaque(false);
            jl.revalidate();
            jl.repaint();
        }

//        if (evnt == 1) {
//            jl.setForeground(Color.BLACK);
//        } else if (evnt == 2) {
//            jl.setForeground(Color.WHITE);
//        }
    }

    private void changeDefButtonColor(JLabel jl, int evnt) {
        if (evnt == 504) {
            jl.setBackground(new java.awt.Color(72, 153, 194));

        } else if (evnt == 505) {
            jl.setBackground(new java.awt.Color(20, 125, 177));
        }
    }

    private void clearAllPanel() {
        panel_dashboard.setVisible(false);
        panel_def.setVisible(false);

    }

    private void removeFrame() {
        try {
            desktoppane_1.remove((Component) iframe);
        } catch (Exception e) {

        }
    }

    private void setLabelName() {
        setDefLabelVisible();
        switch (menuLabel) {
            case 1:
                lbl_1.setText("Manage Subjects");
                lbl_2.setText("Manage Classes");
                lbl_3.setText("Event Shedule");

                lbl_4.setVisible(false);
                lbl_5.setVisible(false);
                lbl_6.setVisible(false);
                break;

            case 2:
                lbl_1.setText("Student Registration");
                lbl_2.setText("Student Payments");
                lbl_3.setText("Payment Types");
                lbl_4.setText("Academic Data Input");
                lbl_5.setText("Student Leave Manage");
                lbl_6.setText("Student Attendance");

                break;
            case 3:
                lbl_1.setText("Lecturer Registration");
                lbl_2.setText("Contracts Manage");
                lbl_3.setText("Payments");

                lbl_4.setVisible(false);
                lbl_5.setVisible(false);
                lbl_6.setVisible(false);
                break;
            case 4:
                lbl_1.setText("Employee Registration");
                lbl_2.setText("Job Role Manage");
                lbl_3.setText("Employee Payments");

                lbl_4.setVisible(false);
                lbl_5.setVisible(false);
                lbl_6.setVisible(false);
                break;
            case 5:
                lbl_1.setText("System User Manage");
                lbl_2.setText("User Type Manage");

                lbl_3.setVisible(false);
                lbl_4.setVisible(false);
                lbl_5.setVisible(false);
                lbl_6.setVisible(false);
                break;
        }

    }

    private void setDefLabelVisible() {
        lbl_1.setVisible(true);
        lbl_2.setVisible(true);
        lbl_3.setVisible(true);
        lbl_4.setVisible(true);
        lbl_5.setVisible(true);
        lbl_6.setVisible(true);

    }

    private void iframeOpen(JLabel j) {
        if (menuLabel == 1) {
            if (j.equals(lbl_1)) {
                iframe = new SubjectManage();
                desktoppane_1.add((Component) iframe).setVisible(true);
            } else if (j.equals(lbl_2)) {
                iframe = new ManageClasses();
                desktoppane_1.add((Component) iframe).setVisible(true);
            } else if (j.equals(lbl_3)) {
                iframe = new Schedule();
                desktoppane_1.add((Component) iframe).setVisible(true);
            }
        } else if (menuLabel == 2) {
            if (j.equals(lbl_1)) {
                iframe = new StudentRegistration();
                desktoppane_1.add((Component) iframe).setVisible(true);
            } else if (j.equals(lbl_2)) {
                iframe = new StudentPayment();
                desktoppane_1.add((Component) iframe).setVisible(true);
            } else if (j.equals(lbl_3)) {
                iframe = new StOtherPaymentType();
                desktoppane_1.add((Component) iframe).setVisible(true);
            } else if (j.equals(lbl_4)) {
                iframe = new AcademicDataInput();
                desktoppane_1.add((Component) iframe).setVisible(true);
            } else if (j.equals(lbl_5)) {
                iframe = new StudentLeave();
                desktoppane_1.add((Component) iframe).setVisible(true);
            } else if (j.equals(lbl_6)) {
                iframe = new StudentAttendance();
                desktoppane_1.add((Component) iframe).setVisible(true);
            }
        } else if (menuLabel == 3) {
            if (j.equals(lbl_1)) {
                iframe = new LecturerRegistration();
                desktoppane_1.add((Component) iframe).setVisible(true);
            } else if (j.equals(lbl_2)) {
                iframe = new LecturerContract();
                desktoppane_1.add((Component) iframe).setVisible(true);
            } else if (j.equals(lbl_3)) {
                iframe = new LecturerPayment();
                desktoppane_1.add((Component) iframe).setVisible(true);
            }
        } else if (menuLabel == 4) {
            if (j.equals(lbl_1)) {

            } else if (j.equals(lbl_2)) {

            } else if (j.equals(lbl_3)) {

            }
        } else if (menuLabel == 5) {
            if (j.equals(lbl_1)) {
                iframe = new SystemUser();
                desktoppane_1.add((Component) iframe).setVisible(true);
            } else if (j.equals(lbl_2)) {
                iframe = new SystemUserType();
                desktoppane_1.add((Component) iframe).setVisible(true);
            }
        }
    }

    private void setDateAndTime() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                date = new Date();
                lbl_date.setText(sdf1.format(date));

            }
        });
        timer.start();
    }

    private void updateJlabels() {
        Timer timer = new Timer(900000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                calculateTodayQuary();
                calculateStudentAmount();
                calculateTotalLecturers();
                calculateRunningContracts();
            }
        });
        timer.start();
    }

    private void calculateTodayQuary() {
        try {

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDateTime now = LocalDateTime.now();
            String date = dtf.format(now) + " 00:00:00";

            ResultSet rs = DB.search("SELECT sum(total_amount) as st FROM student_payment where date_time > '" + date + "'");
            rs.next();
            lbl_total.setText(rs.getString("st"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void calculateStudentAmount() {
        try {
            ResultSet rs = DB.search("select count(id_student) as count from student");
            if (rs.next()) {
                lbl_studentAmount.setText(String.valueOf(rs.getInt("count")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void calculateTotalLecturers() {
        try {
            ResultSet rs = DB.search("select count(id_lecturer) as count from lecturer");
            if (rs.next()) {
                lbl_lecturerAmount.setText(String.valueOf(rs.getInt("count")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void calculateRunningContracts() {
        try {
            ResultSet rs = DB.search("select count(id_contract) as count from lecturer_contract where status='1'");
            if (rs.next()) {
                lbl_contractAmount.setText(String.valueOf(rs.getInt("count")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void checkPermission() {
        String type = getUserType();
        if (!type.equals("admin")) {
            lbl_system.setVisible(false);
            lbl_system.setFocusable(false);
            jButton8.setVisible(false);
            jButton9.setVisible(false);
            jButton10.setVisible(false);

        }
    }

    private void setUserDetails() {
        String systemUser = getEmployee();
        String userType = getUserType();

        lbl_user.setText("SYSTEM USER : " + systemUser);
        lbl_userType.setText("USER PRIVILEGE : " + userType);
    }
    DefaultTableModel dtm1;

    private void addNotes() {
        try {
            ResultSet rs = DB.search("select * from notes");
            while (rs.next()) {
                topic.add(rs.getString("topic"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void setTopics() {
        try {
            lbl_n1.setText(String.valueOf(topic.get(0)));
            lbl_n2.setText(String.valueOf(topic.get(1)));
            lbl_n3.setText(String.valueOf(topic.get(2)));
            lbl_n4.setText(String.valueOf(topic.get(3)));
            lbl_n5.setText(String.valueOf(topic.get(4)));
            lbl_n6.setText(String.valueOf(topic.get(5)));
            lbl_n7.setText(String.valueOf(topic.get(6)));
            lbl_n8.setText(String.valueOf(topic.get(7)));
            lbl_n9.setText(String.valueOf(topic.get(8)));
            lbl_n10.setText(String.valueOf(topic.get(9)));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void getSelecttedNote(JLabel j) {
        try {
            ResultSet rs = DB.search("select * from notes where topic='" + j.getText() + "'");
            if (rs.next()) {
                txt_note.setText(rs.getString("note"));
                txt_topic.setText(rs.getString("topic"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void notesReset() {
        lastIndex = 9;
        firstIndex = 0;
        topic.clear();
        addNotes();
        setTopics();
    }

}
