/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arunaedu.main;

import static com.anuraedu.common.SQ.LIKESEARCH;
import static com.anuraedu.common.SQ.PVTSEARCH4;
import static com.anuraedu.common.SQ.SAVE;
import static com.anuraedu.common.SQ.SEARCH;
import static com.anuraedu.common.SQ.STATUSSEARCH;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import static com.anuraedu.common.SQ.UPDATE;
import static com.anuraedu.common.SQ.getResult;
import com.anuraedu.db.DB;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JLabel;

/**
 *
 * @author ASUS
 */
public class ManageClasses extends javax.swing.JInternalFrame {

    String prevText;
    ArrayList<JTextField> jf;
    ArrayList<String> defaultText;
     DefaultTableModel dtm1;
   
    public ManageClasses() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI) this.getUI();
        bif.setNorthPane(null);
        
        addDefaultTextToList();
        addTextFieldsToList();
        setDefaultText();
        setDefaultTextField();
        
        genarateClassId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_classId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_description = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        rad_active = new javax.swing.JRadioButton();
        rad_inactive = new javax.swing.JRadioButton();
        txt_classFees = new javax.swing.JTextField();
        txt_contractId = new javax.swing.JTextField();
        cbox_classSuggestions = new javax.swing.JCheckBox();
        cbox_classShowAll = new javax.swing.JCheckBox();
        cbox_contractSuggestions = new javax.swing.JCheckBox();
        cbox_contractShowAll = new javax.swing.JCheckBox();
        btn_save = new javax.swing.JLabel();
        btn_update = new javax.swing.JLabel();
        btn_delete = new javax.swing.JLabel();
        btn_delete1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btn_editSelected2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btn_editSelected = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1670, 1040));

        jPanel2.setBackground(new java.awt.Color(111, 187, 217));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 76, 76));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Class ID");

        txt_classId.setEditable(false);
        txt_classId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_classId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_classId.setFocusable(false);
        txt_classId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_classIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_classIdFocusLost(evt);
            }
        });
        txt_classId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_classIdKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 76, 76));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Description");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 76, 76));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Contract ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(76, 76, 76));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Class Fees");

        txt_description.setColumns(20);
        txt_description.setRows(5);
        jScrollPane1.setViewportView(txt_description);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(76, 76, 76));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Status");

        rad_active.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rad_active);
        rad_active.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_active.setSelected(true);
        rad_active.setText("Active");

        rad_inactive.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rad_inactive);
        rad_inactive.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_inactive.setText("Inactive");

        txt_classFees.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_classFees.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_classFees.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_classFeesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_classFeesFocusLost(evt);
            }
        });
        txt_classFees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_classFeesKeyTyped(evt);
            }
        });

        txt_contractId.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_contractId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_contractId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_contractIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_contractIdFocusLost(evt);
            }
        });
        txt_contractId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_contractIdKeyReleased(evt);
            }
        });

        cbox_classSuggestions.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(cbox_classSuggestions);
        cbox_classSuggestions.setSelected(true);
        cbox_classSuggestions.setText("suggestions");
        cbox_classSuggestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_classSuggestionsActionPerformed(evt);
            }
        });

        cbox_classShowAll.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(cbox_classShowAll);
        cbox_classShowAll.setText("show all");
        cbox_classShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_classShowAllActionPerformed(evt);
            }
        });

        cbox_contractSuggestions.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(cbox_contractSuggestions);
        cbox_contractSuggestions.setSelected(true);
        cbox_contractSuggestions.setText("suggestions");
        cbox_contractSuggestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_contractSuggestionsActionPerformed(evt);
            }
        });

        cbox_contractShowAll.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(cbox_contractShowAll);
        cbox_contractShowAll.setText("show all");
        cbox_contractShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_contractShowAllActionPerformed(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(69, 141, 152));
        btn_save.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_save.setText("Save");
        btn_save.setOpaque(true);
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_saveMouseExited(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(69, 141, 152));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_update.setText("Update");
        btn_update.setOpaque(true);
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_updateMouseExited(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(69, 141, 152));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_delete.setText("Delete");
        btn_delete.setOpaque(true);
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deleteMouseExited(evt);
            }
        });

        btn_delete1.setBackground(new java.awt.Color(69, 141, 152));
        btn_delete1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_delete1.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_delete1.setText("Reset");
        btn_delete1.setOpaque(true);
        btn_delete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_delete1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_delete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_delete1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_classId, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rad_active)
                        .addGap(39, 39, 39)
                        .addComponent(rad_inactive))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_classFees, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_contractId, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_delete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbox_classSuggestions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_classShowAll))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbox_contractSuggestions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_contractShowAll)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_classId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbox_classShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbox_classSuggestions, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_contractId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbox_contractSuggestions, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbox_contractShowAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_classFees, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rad_active)
                    .addComponent(rad_inactive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Class ID", "Description", "Contract ID", "Class Fees", "status"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        btn_editSelected2.setBackground(new java.awt.Color(69, 141, 152));
        btn_editSelected2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_editSelected2.setForeground(new java.awt.Color(255, 255, 255));
        btn_editSelected2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editSelected2.setText("Edit selected");
        btn_editSelected2.setOpaque(true);
        btn_editSelected2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editSelected2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editSelected2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editSelected2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btn_editSelected2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_editSelected2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Class Search", jPanel9);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Contract ID", "Description", "Subject ID", "Lecturer ID", "Start Date", "End Date", "Status"
            }
        ));
        jScrollPane7.setViewportView(jTable3);

        btn_editSelected.setBackground(new java.awt.Color(69, 141, 152));
        btn_editSelected.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_editSelected.setForeground(new java.awt.Color(255, 255, 255));
        btn_editSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editSelected.setText("Get selected");
        btn_editSelected.setOpaque(true);
        btn_editSelected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editSelectedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editSelectedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editSelectedMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_editSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_editSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Contract Search", jPanel3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editSelected2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelected2MouseClicked
        txt_classId.setText((String) jTable2.getValueAt(jTable2.getSelectedRow(), 0));
        try {
            SEARCH("class", "id_class", (String) jTable2.getValueAt(jTable2.getSelectedRow(), 0));
            ResultSet rs = getResult();

            if (rs.next()) {
                txt_description.setText(rs.getString("description"));
                txt_contractId.setText(rs.getString("id_contract"));
                txt_classFees.setText(rs.getString("class_fees"));
                
                if (rs.getBoolean("status")) {
                    rad_active.setSelected(true);
                } else {
                    rad_inactive.setSelected(true);
                }

                for (int i = 0; i < jf.size(); i++) {
                    textFieldTextType(0, jf.get(i));
                    if (jf.get(i).getText().equals("")) {
                        jf.get(i).setBackground(new java.awt.Color(253, 237, 237));
                    } else {
                        jf.get(i).setBackground(new java.awt.Color(178, 230, 245));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_editSelected2MouseClicked

    private void btn_editSelected2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelected2MouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_editSelected2MouseEntered

    private void btn_editSelected2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelected2MouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_editSelected2MouseExited

    private void btn_editSelectedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelectedMouseClicked
        txt_contractId.setText((String) jTable3.getValueAt(jTable3.getSelectedRow(), 0));
       txt_contractId.setBackground(new java.awt.Color(178, 230, 245));
        textFieldTextType(0, txt_contractId);
    }//GEN-LAST:event_btn_editSelectedMouseClicked

    private void btn_editSelectedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelectedMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_editSelectedMouseEntered

    private void btn_editSelectedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelectedMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_editSelectedMouseExited

    private void cbox_classSuggestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_classSuggestionsActionPerformed
        if(cbox_classSuggestions.isSelected()){
            jTabbedPane1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cbox_classSuggestionsActionPerformed

    private void cbox_classShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_classShowAllActionPerformed
        if(cbox_classShowAll.isSelected()){
            jTabbedPane1.setSelectedIndex(0);
            removeAllRows(jTable2);
            fillTable(2);
        }
    }//GEN-LAST:event_cbox_classShowAllActionPerformed

    private void cbox_contractShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_contractShowAllActionPerformed
        if(cbox_contractShowAll.isSelected()){
            removeAllRows(jTable3);
            jTabbedPane1.setSelectedIndex(1);
            try {
                SEARCH("lecturer_contract");
                fillTableProcess(3);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_cbox_contractShowAllActionPerformed

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked

        if (checkFields()) {
            int status = (rad_active.isSelected()) ? 1 : 0;

                    try {
                        if(STATUSSEARCH("lecturer_contract", "id_contract", txt_contractId.getText())){
                        SAVE("class", "'"
                            + txt_classId.getText() + "','"
                            + txt_description.getText() + "','"
                            + txt_contractId.getText() + "','"
                            + Double.parseDouble(txt_classFees.getText()) + "','"
                            + status + "'");
                        JOptionPane.showMessageDialog(this, " Saved !");
                        clearFields();
                        if (cbox_classShowAll.isSelected()) {
                            removeAllRows(jTable2);
                            fillTable(2);
                            genarateClassId();
                            txt_description.grabFocus();
                        }
                         }else{
                JOptionPane.showMessageDialog(this, "Contract not Active !");
            }
                    } catch (SQLIntegrityConstraintViolationException ex) {
                        JOptionPane.showMessageDialog(this, "Class ID has already in the DataBase !. The Error Message: " + ex.getMessage());
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

        } else {
            JOptionPane.showMessageDialog(this, "Fill all Fields !");
        }
    }//GEN-LAST:event_btn_saveMouseClicked

    private void btn_saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_saveMouseEntered

    private void btn_saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_saveMouseExited

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked

        int status = (rad_active.isSelected()) ? 1 : 0;
 
        if (checkFields()) {
            try {
                UPDATE("class",
                     "description='" + txt_description.getText()
                    + "',id_contract='" + txt_contractId.getText()
                    + "',class_fees='" + Double.parseDouble(txt_classFees.getText())
                    + "',status='" + status
                    + "'", "id_class",
                    txt_classId.getText());
                JOptionPane.showMessageDialog(this, " Updated !");
                if (cbox_classShowAll.isSelected()) {
                            removeAllRows(jTable2);
                            fillTable(2);
                            genarateClassId();
                            txt_description.grabFocus();
                        }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fill all Fields !");
        }
    }//GEN-LAST:event_btn_updateMouseClicked

    private void btn_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_updateMouseEntered

    private void btn_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_updateMouseExited

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
        try {
            UPDATE("class", "status='0'", "id_class", txt_classId.getText());
            JOptionPane.showMessageDialog(this, "Marked as Inactive !");
            rad_inactive.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_deleteMouseClicked

    private void btn_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_deleteMouseEntered

    private void btn_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_deleteMouseExited

    private void txt_classIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_classIdKeyReleased
        if (cbox_classSuggestions.isSelected()) {
                removeAllRows(jTable2);
                jTabbedPane1.setSelectedIndex(0);
               try {
                    LIKESEARCH("class", "id_class", txt_classId.getText());
                    
                    fillTableProcess(2);
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
    }//GEN-LAST:event_txt_classIdKeyReleased

    private void cbox_contractSuggestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_contractSuggestionsActionPerformed
        if(cbox_contractSuggestions.isSelected()){
            jTabbedPane1.setSelectedIndex(1);
        }
    }//GEN-LAST:event_cbox_contractSuggestionsActionPerformed

    private void txt_contractIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contractIdKeyReleased
        if (cbox_contractSuggestions.isSelected()) {
                removeAllRows(jTable3);
                jTabbedPane1.setSelectedIndex(1);
               try { 
                    LIKESEARCH("lecturer_contract", "id_contract", txt_contractId.getText());
                    fillTableProcess(3);
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
    }//GEN-LAST:event_txt_contractIdKeyReleased

    private void txt_classIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_classIdFocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_classIdFocusGained

    private void txt_classIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_classIdFocusLost
       warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_classIdFocusLost

    private void txt_contractIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contractIdFocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_contractIdFocusGained

    private void txt_contractIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contractIdFocusLost
       warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_contractIdFocusLost

    private void txt_classFeesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_classFeesFocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_classFeesFocusGained

    private void txt_classFeesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_classFeesFocusLost
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_classFeesFocusLost
private boolean point = false;
    private void txt_classFeesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_classFeesKeyTyped
            char Char = evt.getKeyChar();
    if (txt_classFees.getText().equals(""))
        point = false;
    if (point == false){
        if (Char == '.') point = true;
        else if (!(Character.isDigit(Char) || (Char == KeyEvent.VK_BACK_SPACE) || (Char == KeyEvent.VK_DELETE))) {
                evt.consume();
        }
    } else {
        if (!(Character.isDigit(Char) || (Char == KeyEvent.VK_BACK_SPACE) || (Char == KeyEvent.VK_DELETE))) {
                evt.consume();
        }
    }
    }//GEN-LAST:event_txt_classFeesKeyTyped

    private void btn_delete1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_delete1MouseClicked
        clearFields();
        genarateClassId();
        
    }//GEN-LAST:event_btn_delete1MouseClicked

    private void btn_delete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_delete1MouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_delete1MouseEntered

    private void btn_delete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_delete1MouseExited
         colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_delete1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_delete;
    private javax.swing.JLabel btn_delete1;
    private javax.swing.JLabel btn_editSelected;
    private javax.swing.JLabel btn_editSelected2;
    private javax.swing.JLabel btn_save;
    private javax.swing.JLabel btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox cbox_classShowAll;
    private javax.swing.JCheckBox cbox_classSuggestions;
    private javax.swing.JCheckBox cbox_contractShowAll;
    private javax.swing.JCheckBox cbox_contractSuggestions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JRadioButton rad_active;
    private javax.swing.JRadioButton rad_inactive;
    private javax.swing.JTextField txt_classFees;
    private javax.swing.JTextField txt_classId;
    private javax.swing.JTextField txt_contractId;
    private javax.swing.JTextArea txt_description;
    // End of variables declaration//GEN-END:variables

    private boolean checkFields() {

        if (txt_description.getText().equals("")
                && txt_contractId.getText().equals("")
                && txt_classFees.getText().equals("")
                ) {
            return false;
        } else {
            return true;
        }

    }

    private void colorButtons(int i, JLabel jl) {
        if (i == 504) {
            jl.setBackground(new java.awt.Color(117, 170, 179));

        } else if (i == 505) {
            jl.setBackground(new java.awt.Color(69, 141, 152));
        }
    }
    
    private void textFieldTextType(int i, JTextField jt) {
        if (i == 0) {
            jt.setForeground(new java.awt.Color(0, 0, 0));
            Font f = new Font("Tahoma", 0, 16);
            jt.setFont(f);
        } else if (i == 1) {
            jt.setForeground(new java.awt.Color(124, 124, 124));
            Font f = new Font("Tahoma", 0, 14);
            jt.setFont(f);
        }

    }

    private void setDefaultTextField() {
        for (JTextField jTextField : jf) {
            jTextField.setBackground(new java.awt.Color(253, 237, 237));
            jTextField.setForeground(new java.awt.Color(124, 124, 124));
            Font f = new Font("Tahoma", 0, 14);
            jTextField.setFont(f);
        }
    }

    private void addTextFieldsToList() {
        jf = new ArrayList<JTextField>();
       
        jf.add(txt_contractId);
        jf.add(txt_classFees);

    }

    private void addDefaultTextToList() {
        defaultText = new ArrayList<String>();
        
        defaultText.add("Contract ID");
        defaultText.add("0");

    }

    private void setDefaultText() {
        for (int i = 0; i < defaultText.size(); i++) {
            jf.get(i).setText(defaultText.get(i));
        }
    }

    private void clearFields() {
        
        setDefaultText();
        setDefaultTextField();
        txt_description.setText("");
        rad_active.setSelected(true);
    }
    private void warnningLabel(int id, JTextField jTextField) {

        if (id == 1004) {
            if (jTextField.getFont().getSize() == 14) {
                prevText = jTextField.getText();
                jTextField.setText("");
                textFieldTextType(0, jTextField);

            }
            jTextField.setBackground(new java.awt.Color(218, 243, 250));
        } else if (id == 1005) {
            if (jTextField.getText().equals("")) {
                jTextField.setText(prevText);
                textFieldTextType(1, jTextField);
                prevText = null;
                jTextField.setBackground(new java.awt.Color(253, 237, 237));

            } else {
                prevText = null;
                jTextField.setBackground(new java.awt.Color(178, 230, 245));
            }
        }

    }
    private void removeAllRows(JTable j) {
        for (int i = j.getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) j.getModel()).removeRow(i);
        }
    }
    private void fillTable(int i) {
        try {
            SEARCH("class");
            fillTableProcess(i);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     private void fillTableProcess(int i) {
        
         try { 
             if(i==3){
            ResultSet rs = getResult();
            while (rs.next()) {
                
                String id_contract = rs.getString("id_contract");
                String description = rs.getString("description");
                String id_lecturer = rs.getString("id_lecturer");
                String id_subject = rs.getString("id_subject");
                String start_date = rs.getString("start_date");
                String end_date = rs.getString("end_date");
                boolean status = rs.getBoolean("status");

                Vector v = new Vector();

                v.add(id_contract);
                v.add(description);
                v.add(id_subject);
                v.add(id_lecturer);
                v.add(start_date);
                v.add(end_date);
                if (status) {
                    v.add("Active");
                } else {
                    v.add("Inactive");
                }

                dtm1 = (DefaultTableModel) jTable3.getModel();
                dtm1.addRow(v);
            }

            }else if(i==2){
                ResultSet rs = getResult();
                
                while (rs.next()) {
                    
                String id_class = rs.getString("id_class");
                String description = rs.getString("description");
                String id_contract = rs.getString("id_contract");
                String class_fees = String.valueOf(rs.getDouble("class_fees"));
                boolean status = rs.getBoolean("status");

                Vector v = new Vector();

                v.add(id_class);
                v.add(description);
                v.add(id_contract);
                v.add(class_fees);
                if (status) {
                    v.add("Active");
                } else {
                    v.add("Inactive");
                }

                dtm1 = (DefaultTableModel) jTable2.getModel();
                dtm1.addRow(v);
            }
            }
             
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void genarateClassId() {
        try {
            ResultSet rs = DB.search("select count(*) as cls_count from class");
            if (rs.next()) {
                int count = rs.getInt("cls_count");
                String classid = "AECLSS" + (++count);
                txt_classId.setText(classid);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
}
