/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arunaedu.main;

import static com.anuraedu.common.SQ.LIKESEARCH;
import static com.anuraedu.common.SQ.SAVE;
import static com.anuraedu.common.SQ.SEARCH;
import static com.anuraedu.common.SQ.UPDATE;
import static com.anuraedu.common.SQ.getResult;
import com.anuraedu.db.DB;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class StOtherPaymentType extends javax.swing.JInternalFrame {

    DefaultTableModel dtm1;
    String startDate, endDate, prevText;
    ArrayList<JTextField> jf;
    ArrayList<String> defaultText;

    public StOtherPaymentType() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI) this.getUI();
        bif.setNorthPane(null);

        addDefaultTextToList();
        addTextFieldsToList();
        setDefaultText();
        setDefaultTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_paymentid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rad_active = new javax.swing.JRadioButton();
        rad_inactive = new javax.swing.JRadioButton();
        btn_save = new javax.swing.JLabel();
        btn_update = new javax.swing.JLabel();
        btn_delete = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_description = new javax.swing.JTextArea();
        cbox_suggestion = new javax.swing.JCheckBox();
        cbox_showall = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_getSelected = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1670, 1040));

        jPanel2.setBackground(new java.awt.Color(111, 187, 217));

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(76, 76, 76));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(" Payment Type ID");

        txt_paymentid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_paymentid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_paymentid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_paymentidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_paymentidFocusLost(evt);
            }
        });
        txt_paymentid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_paymentidKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 76, 76));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Description");

        txt_amount.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_amount.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_amount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_amountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_amountFocusLost(evt);
            }
        });
        txt_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_amountKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 76, 76));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Amount");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(76, 76, 76));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Status");

        buttonGroup1.add(rad_active);
        rad_active.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_active.setSelected(true);
        rad_active.setText("Active");

        buttonGroup1.add(rad_inactive);
        rad_inactive.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad_inactive.setText("Inactive");

        btn_save.setBackground(new java.awt.Color(69, 141, 152));
        btn_save.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_save.setText("Save");
        btn_save.setOpaque(true);
        btn_save.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_saveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_saveFocusLost(evt);
            }
        });
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(69, 141, 152));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_update.setText("Update");
        btn_update.setOpaque(true);
        btn_update.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_updateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_updateFocusLost(evt);
            }
        });
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(69, 141, 152));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_delete.setText("Delete");
        btn_delete.setOpaque(true);
        btn_delete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_deleteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_deleteFocusLost(evt);
            }
        });
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
        });

        txt_description.setColumns(20);
        txt_description.setRows(5);
        jScrollPane1.setViewportView(txt_description);

        buttonGroup2.add(cbox_suggestion);
        cbox_suggestion.setSelected(true);
        cbox_suggestion.setText("suggestions");

        buttonGroup2.add(cbox_showall);
        cbox_showall.setText("Show all");
        cbox_showall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_showallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txt_paymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rad_active)
                                .addGap(39, 39, 39)
                                .addComponent(rad_inactive))
                            .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbox_suggestion)
                    .addComponent(cbox_showall))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_paymentid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbox_suggestion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbox_showall)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rad_active)
                    .addComponent(rad_inactive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(481, 481, 481))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Description", "Amount", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btn_getSelected.setBackground(new java.awt.Color(69, 141, 152));
        btn_getSelected.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_getSelected.setForeground(new java.awt.Color(255, 255, 255));
        btn_getSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_getSelected.setText("Get Selected");
        btn_getSelected.setOpaque(true);
        btn_getSelected.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_getSelectedFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btn_getSelectedFocusLost(evt);
            }
        });
        btn_getSelected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_getSelectedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_getSelectedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_getSelectedMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_getSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_getSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbox_showallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_showallActionPerformed
        if (cbox_showall.isSelected()) {
            removeAllRows(jTable1);
            fillTable();
        }
    }//GEN-LAST:event_cbox_showallActionPerformed

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        int status = (rad_active.isSelected()) ? 1 : 0;

        if (checkFields()) {

            try {
                SAVE("stdother_paymenttype", "'"
                        + txt_paymentid.getText() + "','"
                        + txt_description.getText() + "','"
                        + Double.parseDouble(txt_amount.getText()) + "','"
                        + status + "'");
                JOptionPane.showMessageDialog(this, " Saved !");
                clearFields();
 if(cbox_showall.isSelected()){
        removeAllRows(jTable1);
        fillTable();
        }
            } catch (SQLIntegrityConstraintViolationException ex) {
                JOptionPane.showMessageDialog(this, "Payment ID has already in the DataBase !. The Error Message: " + ex.getMessage());
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fill all Fields !");
        }
    }//GEN-LAST:event_btn_saveMouseClicked

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked
        int status = (rad_active.isSelected()) ? 1 : 0;
        if (checkFields()) {
            try {
                ResultSet rs = DB.search("select count(1) as rowCount from stdother_paymenttype where id_paymenttype='" + txt_paymentid.getText() + "'");
                rs.next();
                if (rs.getInt("rowCount") != 0) {
                
                UPDATE("stdother_paymenttype",
                        "description='" + txt_description.getText()
                        + "',amount='" + Double.parseDouble(txt_amount.getText())
                        + "',status='" + status
                        + "'", "id_paymenttype",
                        txt_paymentid.getText());
                JOptionPane.showMessageDialog(this, " Updated !");
                 if(cbox_showall.isSelected()){
        removeAllRows(jTable1);
        fillTable();
        }
                 } else {
                    JOptionPane.showMessageDialog(this, "Payment Type ID is not same !");
                }

            } catch (SQLIntegrityConstraintViolationException ex) {
                JOptionPane.showMessageDialog(this, "Payment ID has already in the DataBase !. The Error Message: " + ex.getMessage());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fill all Fields !");
        }
    }//GEN-LAST:event_btn_updateMouseClicked

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
        try {
            UPDATE("stdother_paymenttype", "status='0'", "id_paymenttype", txt_paymentid.getText());
            JOptionPane.showMessageDialog(this, "Marked as Inactive !");
            rad_inactive.setSelected(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_deleteMouseClicked

    private void btn_getSelectedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_getSelectedMouseClicked
        txt_paymentid.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        try {
            SEARCH("stdother_paymenttype", "id_paymenttype", (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            ResultSet rs = getResult();

            if (rs.next()) {
                txt_paymentid.setText(rs.getString("id_paymenttype"));
                txt_description.setText(rs.getString("description"));
                txt_amount.setText(Double.toString(rs.getDouble("amount")));

                if (rs.getBoolean("status")) {
                    rad_active.setSelected(true);
                } else {
                    rad_inactive.setSelected(true);
                }

                for (int i = 0; i < jf.size(); i++) {
                    textFieldTextType(0, jf.get(i));
                    if (jf.get(i).getText().equals("")) {
                        jf.get(i).setBackground(new java.awt.Color(253, 237, 237));
                    } else {
                        jf.get(i).setBackground(new java.awt.Color(178, 230, 245));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_getSelectedMouseClicked

    private void btn_getSelectedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_getSelectedMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_getSelectedMouseEntered

    private void btn_getSelectedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_getSelectedMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_getSelectedMouseExited

    private void txt_paymentidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paymentidKeyReleased
        if (cbox_suggestion.isSelected()) {
            removeAllRows(jTable1);

            try {
                LIKESEARCH("stdother_paymenttype", "id_paymenttype", txt_paymentid.getText());
                fillTableProcess();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_txt_paymentidKeyReleased

    private void txt_paymentidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_paymentidFocusGained

        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_paymentidFocusGained

    private void txt_paymentidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_paymentidFocusLost

        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_paymentidFocusLost

    private void txt_amountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_amountFocusGained

        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_amountFocusGained

    private void txt_amountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_amountFocusLost

        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_amountFocusLost

    private void btn_saveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_saveFocusGained
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_saveFocusGained

    private void btn_saveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_saveFocusLost
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_saveFocusLost

    private void btn_updateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_updateFocusGained
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_updateFocusGained

    private void btn_updateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_updateFocusLost
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_updateFocusLost

    private void btn_deleteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_deleteFocusGained
       colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_deleteFocusGained

    private void btn_deleteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_deleteFocusLost
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_deleteFocusLost

    private void btn_getSelectedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_getSelectedFocusGained
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_getSelectedFocusGained

    private void btn_getSelectedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_getSelectedFocusLost
       colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_getSelectedFocusLost
private boolean point = false;
    private void txt_amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amountKeyTyped
       char Char = evt.getKeyChar();
    if (txt_amount.getText().equals(""))
        point = false;
    if (point == false){
        if (Char == '.') point = true;
        else if (!(Character.isDigit(Char) || (Char == KeyEvent.VK_BACK_SPACE) || (Char == KeyEvent.VK_DELETE))) {
                evt.consume();
        }
    } else {
        if (!(Character.isDigit(Char) || (Char == KeyEvent.VK_BACK_SPACE) || (Char == KeyEvent.VK_DELETE))) {
                evt.consume();
        }
    }
    }//GEN-LAST:event_txt_amountKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_delete;
    private javax.swing.JLabel btn_getSelected;
    private javax.swing.JLabel btn_save;
    private javax.swing.JLabel btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox cbox_showall;
    private javax.swing.JCheckBox cbox_suggestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rad_active;
    private javax.swing.JRadioButton rad_inactive;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextArea txt_description;
    private javax.swing.JTextField txt_paymentid;
    // End of variables declaration//GEN-END:variables

    private void removeAllRows(JTable j) {
        for (int i = j.getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) j.getModel()).removeRow(i);
        }
    }

    private void fillTable() {
        try {
            SEARCH("stdother_paymenttype");
            fillTableProcess();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillTableProcess() {

        try {

            ResultSet rs = getResult();
            while (rs.next()) {

                String id_paymenttype = rs.getString("id_paymenttype");
                String description = rs.getString("description");
                String amount = Double.toString(rs.getDouble("amount"));
                boolean status = rs.getBoolean("status");

                Vector v = new Vector();

                v.add(id_paymenttype);
                v.add(description);
                v.add(amount);
                if (status) {
                    v.add("Active");
                } else {
                    v.add("Inactive");
                }

                dtm1 = (DefaultTableModel) jTable1.getModel();
                dtm1.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean checkFields() {

        if (txt_paymentid.getText().equals("")
                && txt_description.getText().equals("")
                && txt_amount.getText().equals("")) {
            return false;
        } else {
            return true;
        }

    }

    private void colorButtons(int i, JLabel jl) {
        if (i == 504) {
            jl.setBackground(new java.awt.Color(117, 170, 179));

        } else if (i == 505) {
            jl.setBackground(new java.awt.Color(69, 141, 152));
        }
    }

    private void textFieldTextType(int i, JTextField jt) {
        if (i == 0) {
            jt.setForeground(new java.awt.Color(0, 0, 0));
            Font f = new Font("Tahoma", 0, 16);
            jt.setFont(f);
        } else if (i == 1) {
            jt.setForeground(new java.awt.Color(124, 124, 124));
            Font f = new Font("Tahoma", 0, 14);
            jt.setFont(f);
        }

    }

    private void setDefaultTextField() {
        for (JTextField jTextField : jf) {
            jTextField.setBackground(new java.awt.Color(253, 237, 237));
            jTextField.setForeground(new java.awt.Color(124, 124, 124));
            Font f = new Font("Tahoma", 0, 14);
            jTextField.setFont(f);
        }
    }

    private void addTextFieldsToList() {
        jf = new ArrayList<JTextField>();
        jf.add(txt_paymentid);
        jf.add(txt_amount);

    }

    private void addDefaultTextToList() {
        defaultText = new ArrayList<String>();
        defaultText.add("Payment ID");
        defaultText.add("Amount,Rs..");

    }

    private void setDefaultText() {
        for (int i = 0; i < defaultText.size(); i++) {
            jf.get(i).setText(defaultText.get(i));
        }
    }

    private void clearFields() {

        setDefaultText();
        setDefaultTextField();
        txt_description.setText("");
        rad_active.setSelected(true);
    }

    private void warnningLabel(int id, JTextField jTextField) {

        if (id == 1004) {
            if (jTextField.getFont().getSize() == 14) {
                prevText = jTextField.getText();
                jTextField.setText("");
                textFieldTextType(0, jTextField);

            }
            jTextField.setBackground(new java.awt.Color(218, 243, 250));
        } else if (id == 1005) {
            if (jTextField.getText().equals("")) {
                jTextField.setText(prevText);
                textFieldTextType(1, jTextField);
                prevText = null;
                jTextField.setBackground(new java.awt.Color(253, 237, 237));

            } else {
                prevText = null;
                jTextField.setBackground(new java.awt.Color(178, 230, 245));
            }
        }

    }

}
