/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arunaedu.main;

import static com.anuraedu.common.SQ.LIKESEARCH;
import static com.anuraedu.common.SQ.SAVE;
import static com.anuraedu.common.SQ.SEARCH;
import static com.anuraedu.common.SQ.UPDATE;
import static com.anuraedu.common.SQ.getResult;
import com.anuraedu.db.DB;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class SubjectManage extends javax.swing.JInternalFrame {

    ArrayList<JTextField> jf;
    ArrayList<String> defaultText;
    String prevText;
    DefaultTableModel dtm1;

    public SubjectManage() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI) this.getUI();
        bif.setNorthPane(null);

        addDefaultTextToList();
        addTextFieldsToList();
        setDefaultText();
        setDefaultTextField();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_subjectid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_description = new javax.swing.JTextArea();
        txt_contractPersonsLimit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_save = new javax.swing.JLabel();
        btn_delete = new javax.swing.JLabel();
        btn_resetMain = new javax.swing.JLabel();
        btn_update = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rad_inactive = new javax.swing.JRadioButton();
        rad_active = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_1 = new javax.swing.JTable();
        txt_searchBox = new javax.swing.JTextField();
        cbox_subjectId = new javax.swing.JCheckBox();
        cbox_showSuggetions = new javax.swing.JCheckBox();
        btn_searchInSearch = new javax.swing.JLabel();
        btn_showAll = new javax.swing.JLabel();
        btn_editSelected = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1670, 1040));

        jPanel1.setBackground(new java.awt.Color(111, 187, 217));

        txt_subjectid.setBackground(new java.awt.Color(178, 230, 245));
        txt_subjectid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_subjectid.setForeground(new java.awt.Color(124, 124, 124));
        txt_subjectid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_subjectid.setToolTipText("");
        txt_subjectid.setVerifyInputWhenFocusTarget(false);
        txt_subjectid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_subjectidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_subjectidFocusLost(evt);
            }
        });
        txt_subjectid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subjectidActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(76, 76, 76));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Subject ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(76, 76, 76));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Description");

        txt_description.setBackground(new java.awt.Color(178, 230, 245));
        txt_description.setColumns(20);
        txt_description.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_description.setRows(5);
        jScrollPane1.setViewportView(txt_description);

        txt_contractPersonsLimit.setBackground(new java.awt.Color(178, 230, 245));
        txt_contractPersonsLimit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_contractPersonsLimit.setForeground(new java.awt.Color(124, 124, 124));
        txt_contractPersonsLimit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_contractPersonsLimit.setToolTipText("");
        txt_contractPersonsLimit.setVerifyInputWhenFocusTarget(false);
        txt_contractPersonsLimit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_contractPersonsLimitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_contractPersonsLimitFocusLost(evt);
            }
        });
        txt_contractPersonsLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contractPersonsLimitActionPerformed(evt);
            }
        });
        txt_contractPersonsLimit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_contractPersonsLimitKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contractPersonsLimitKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(76, 76, 76));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Contract, persons limit");

        btn_save.setBackground(new java.awt.Color(69, 141, 152));
        btn_save.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_save.setText("Save");
        btn_save.setOpaque(true);
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_saveMouseExited(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(69, 141, 152));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_delete.setText("Delete");
        btn_delete.setOpaque(true);
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deleteMouseExited(evt);
            }
        });

        btn_resetMain.setBackground(new java.awt.Color(69, 141, 152));
        btn_resetMain.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_resetMain.setForeground(new java.awt.Color(255, 255, 255));
        btn_resetMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_resetMain.setText("Reset");
        btn_resetMain.setOpaque(true);
        btn_resetMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetMainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_resetMainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_resetMainMouseExited(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(69, 141, 152));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_update.setText("Update");
        btn_update.setOpaque(true);
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_updateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_updateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_updateMouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(20, 125, 177));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Manage Subjects");
        jLabel11.setOpaque(true);

        rad_inactive.setBackground(new java.awt.Color(218, 243, 250));
        buttonGroup1.add(rad_inactive);
        rad_inactive.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rad_inactive.setText("Inactive");

        rad_active.setBackground(new java.awt.Color(218, 243, 250));
        buttonGroup1.add(rad_active);
        rad_active.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        rad_active.setSelected(true);
        rad_active.setText("Active");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(76, 76, 76));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Subject status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rad_active)
                                        .addGap(26, 26, 26)
                                        .addComponent(rad_inactive)))
                                .addGap(148, 148, 148))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_contractPersonsLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_subjectid)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_resetMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_subjectid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_resetMain, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_contractPersonsLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_active)
                    .addComponent(rad_inactive))
                .addContainerGap(368, Short.MAX_VALUE))
        );

        Table_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject ID", "Description", "Max Contracts", "Status"
            }
        ));
        jScrollPane2.setViewportView(Table_1);

        txt_searchBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_searchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchBoxKeyReleased(evt);
            }
        });

        cbox_subjectId.setSelected(true);
        cbox_subjectId.setText("Subject ID");

        cbox_showSuggetions.setText("Show Suggestions");

        btn_searchInSearch.setBackground(new java.awt.Color(69, 141, 152));
        btn_searchInSearch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_searchInSearch.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchInSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_searchInSearch.setText("Search");
        btn_searchInSearch.setOpaque(true);
        btn_searchInSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchInSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchInSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchInSearchMouseExited(evt);
            }
        });

        btn_showAll.setBackground(new java.awt.Color(69, 141, 152));
        btn_showAll.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_showAll.setForeground(new java.awt.Color(255, 255, 255));
        btn_showAll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_showAll.setText("Show All");
        btn_showAll.setOpaque(true);
        btn_showAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showAllMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_showAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_showAllMouseExited(evt);
            }
        });

        btn_editSelected.setBackground(new java.awt.Color(69, 141, 152));
        btn_editSelected.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_editSelected.setForeground(new java.awt.Color(255, 255, 255));
        btn_editSelected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_editSelected.setText("Edit Selected");
        btn_editSelected.setOpaque(true);
        btn_editSelected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editSelectedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editSelectedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editSelectedMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cbox_subjectId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbox_showSuggetions)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_editSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_searchInSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_showAll, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 105, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_showAll, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_searchBox)
                            .addComponent(btn_searchInSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbox_showSuggetions)
                                .addComponent(cbox_subjectId))
                            .addComponent(btn_editSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_subjectidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_subjectidFocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_subjectidFocusGained

    private void txt_subjectidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_subjectidFocusLost
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_subjectidFocusLost

    private void txt_subjectidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subjectidActionPerformed
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_subjectidActionPerformed

    private void txt_contractPersonsLimitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contractPersonsLimitFocusGained
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_contractPersonsLimitFocusGained

    private void txt_contractPersonsLimitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contractPersonsLimitFocusLost
        warnningLabel(evt.getID(), (JTextField) evt.getSource());
    }//GEN-LAST:event_txt_contractPersonsLimitFocusLost

    private void txt_contractPersonsLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contractPersonsLimitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contractPersonsLimitActionPerformed

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked

        int status = (rad_active.isSelected()) ? 1 : 0;

        if (checkFields()) {
            try {
                SAVE("subject", "'"
                        + txt_subjectid.getText() + "','"
                        + txt_description.getText() + "','"
                        + Integer.valueOf(txt_contractPersonsLimit.getText()) + "','"
                        + status + "'");
                JOptionPane.showMessageDialog(this, " Saved !");
                clearFields();
                removeAllRows();
                fillTable();

                txt_subjectid.grabFocus();
            } catch (SQLIntegrityConstraintViolationException ex) {
                JOptionPane.showMessageDialog(this, "subject ID has already in the DataBase !. The Error Message: " + ex.getMessage());
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fill all Fields !");
        }
    }//GEN-LAST:event_btn_saveMouseClicked

    private void btn_saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_saveMouseEntered

    private void btn_saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_saveMouseExited

    private void btn_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseClicked

        int status = (rad_active.isSelected()) ? 1 : 0;

        if (checkFields()) {

            try {
                ResultSet rs = DB.search("select count(1) as rowCount from subject where id_subject='" + txt_subjectid.getText() + "'");
                rs.next();
                if (rs.getInt("rowCount") != 0) {
                    UPDATE("subject",
                            "description='" + txt_description.getText()
                            + "',maxcontracts_number='" + Integer.valueOf(txt_contractPersonsLimit.getText())
                            + "',status='" + status
                            + "'", "id_subject",
                            txt_subjectid.getText());

                    JOptionPane.showMessageDialog(this, " Updated !");
                    removeAllRows();
                    fillTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Subject ID is not same !");
                }

            } catch (SQLIntegrityConstraintViolationException ex) {
                JOptionPane.showMessageDialog(this, "subject ID has already in the DataBase !. The Error Message: " + ex.getMessage());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fill all Fields !");
        }

    }//GEN-LAST:event_btn_updateMouseClicked

    private void btn_updateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_updateMouseEntered

    private void btn_updateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_updateMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_updateMouseExited

    private void btn_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseClicked
        try {
            UPDATE("subject", "status='0'", "id_subject", txt_subjectid.getText());
            JOptionPane.showMessageDialog(this, "Marked as Inactive !");
            rad_inactive.setSelected(true);
            removeAllRows();
            fillTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_deleteMouseClicked

    private void btn_deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_deleteMouseEntered

    private void btn_deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deleteMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_deleteMouseExited

    private void btn_resetMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMainMouseClicked
        clearFields();
    }//GEN-LAST:event_btn_resetMainMouseClicked

    private void btn_resetMainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMainMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_resetMainMouseEntered

    private void btn_resetMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMainMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_resetMainMouseExited

    private void txt_searchBoxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchBoxKeyReleased
        if (cbox_showSuggetions.isSelected()) {
            removeAllRows();
            if (cbox_subjectId.isSelected()) {
                try {
                    LIKESEARCH("subject", "id_subject", txt_searchBox.getText());
                    fillTableProcess();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_txt_searchBoxKeyReleased

    private void btn_searchInSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchInSearchMouseClicked

        removeAllRows();
        if (cbox_subjectId.isSelected()) {
            try {
                SEARCH("subject", "id_subject", txt_searchBox.getText());
                ResultSet rs = getResult();
                if (rs.next()) {

                    String id_subject = rs.getString("id_subject");
                    String description = rs.getString("description");
                    String maxcontracts_number = rs.getString("maxcontracts_number");

                    boolean status = rs.getBoolean("status");

                    Vector v = new Vector();

                    v.add(id_subject);
                    v.add(description);
                    v.add(maxcontracts_number);

                    if (status) {
                        v.add("Active");
                    } else {
                        v.add("Inactive");
                    }

                    dtm1 = (DefaultTableModel) Table_1.getModel();
                    dtm1.addRow(v);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_searchInSearchMouseClicked

    private void btn_searchInSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchInSearchMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_searchInSearchMouseEntered

    private void btn_searchInSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchInSearchMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_searchInSearchMouseExited

    private void btn_showAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showAllMouseClicked
        removeAllRows();
        fillTable();
    }//GEN-LAST:event_btn_showAllMouseClicked

    private void btn_showAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showAllMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_showAllMouseEntered

    private void btn_showAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showAllMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_showAllMouseExited

    private void btn_editSelectedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelectedMouseClicked
//        txt_subjectid.setText((String) Table_1.getValueAt(Table_1.getSelectedRow(), 0));

        try {
            SEARCH("subject", "id_subject", (String) Table_1.getValueAt(Table_1.getSelectedRow(), 0));
            ResultSet rs = getResult();

            if (rs.next()) {
                txt_subjectid.setText(rs.getString("id_subject"));
                txt_description.setText(rs.getString("description"));
                txt_contractPersonsLimit.setText(rs.getString("maxcontracts_number"));

                if (rs.getBoolean("status")) {
                    rad_active.setSelected(true);
                } else {
                    rad_inactive.setSelected(true);
                }

                for (int i = 0; i < jf.size(); i++) {
                    textFieldTextType(0, jf.get(i));
                    if (jf.get(i).getText().equals("")) {
                        jf.get(i).setBackground(new java.awt.Color(253, 237, 237));
                    } else {
                        jf.get(i).setBackground(new java.awt.Color(178, 230, 245));
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_editSelectedMouseClicked

    private void btn_editSelectedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelectedMouseEntered
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_editSelectedMouseEntered

    private void btn_editSelectedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editSelectedMouseExited
        colorButtons(evt.getID(), (JLabel) evt.getSource());
    }//GEN-LAST:event_btn_editSelectedMouseExited

    private void txt_contractPersonsLimitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contractPersonsLimitKeyTyped
        char keyChar = evt.getKeyChar();
        boolean digit = Character.isDigit(keyChar);
        if (digit) {

        } else {
            evt.consume();
        }


    }//GEN-LAST:event_txt_contractPersonsLimitKeyTyped

    private void txt_contractPersonsLimitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contractPersonsLimitKeyPressed

    }//GEN-LAST:event_txt_contractPersonsLimitKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_1;
    private javax.swing.JLabel btn_delete;
    private javax.swing.JLabel btn_editSelected;
    private javax.swing.JLabel btn_resetMain;
    private javax.swing.JLabel btn_save;
    private javax.swing.JLabel btn_searchInSearch;
    private javax.swing.JLabel btn_showAll;
    private javax.swing.JLabel btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbox_showSuggetions;
    private javax.swing.JCheckBox cbox_subjectId;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rad_active;
    private javax.swing.JRadioButton rad_inactive;
    private javax.swing.JTextField txt_contractPersonsLimit;
    private javax.swing.JTextArea txt_description;
    private javax.swing.JTextField txt_searchBox;
    private javax.swing.JTextField txt_subjectid;
    // End of variables declaration//GEN-END:variables

    private void warnningLabel(int id, JTextField jTextField) {

        if (id == 1004) {
            if (jTextField.getFont().getSize() == 14) {
                prevText = jTextField.getText();
                jTextField.setText("");
                textFieldTextType(0, jTextField);

            }
            jTextField.setBackground(new java.awt.Color(218, 243, 250));
        } else if (id == 1005) {
            if (jTextField.getText().equals("")) {
                jTextField.setText(prevText);
                textFieldTextType(1, jTextField);
                prevText = null;
                jTextField.setBackground(new java.awt.Color(253, 237, 237));

            } else {
                prevText = null;
                jTextField.setBackground(new java.awt.Color(178, 230, 245));
            }
        }

    }

    private void textFieldTextType(int i, JTextField jt) {
        if (i == 0) {
            jt.setForeground(new java.awt.Color(0, 0, 0));
            Font f = new Font("Tahoma", 0, 16);
            jt.setFont(f);
        } else if (i == 1) {
            jt.setForeground(new java.awt.Color(124, 124, 124));
            Font f = new Font("Tahoma", 0, 14);
            jt.setFont(f);
        }

    }

    private void setDefaultTextField() {
        for (JTextField jTextField : jf) {
            jTextField.setBackground(new java.awt.Color(253, 237, 237));
            jTextField.setForeground(new java.awt.Color(124, 124, 124));
            Font f = new Font("Tahoma", 0, 14);
            jTextField.setFont(f);
        }
    }

    private void addTextFieldsToList() {
        jf = new ArrayList<JTextField>();
        jf.add(txt_subjectid);
        jf.add(txt_contractPersonsLimit);

    }

    private void addDefaultTextToList() {
        defaultText = new ArrayList<String>();
        defaultText.add("Enter ID");
        defaultText.add("Contract Limit");

    }

    private void setDefaultText() {
        for (int i = 0; i < defaultText.size(); i++) {
            jf.get(i).setText(defaultText.get(i));
        }
    }

    private boolean checkFields() {

        if (txt_subjectid.getText().equals("")
                && txt_subjectid.getText().equals("")
                && txt_description.getText().equals("")
                && txt_contractPersonsLimit.getText().equals("")) {
            return false;
        } else {
            return true;
        }

    }

    private void clearFields() {
        setDefaultText();
        setDefaultTextField();
        txt_description.setText("");
        rad_active.setSelected(true);
        txt_subjectid.grabFocus();
    }

    private void removeAllRows() {
        for (int i = Table_1.getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) Table_1.getModel()).removeRow(i);
        }
    }

    private void fillTable() {
        try {
            SEARCH("subject");
            fillTableProcess();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void fillTableProcess() {

        try {

            ResultSet rs = getResult();
            while (rs.next()) {

                String id_subject = rs.getString("id_subject");
                String description = rs.getString("description");
                String maxcontracts_number = rs.getString("maxcontracts_number");

                boolean status = rs.getBoolean("status");

                Vector v = new Vector();

                v.add(id_subject);
                v.add(description);
                v.add(maxcontracts_number);

                if (status) {
                    v.add("Active");
                } else {
                    v.add("Inactive");
                }

                dtm1 = (DefaultTableModel) Table_1.getModel();
                dtm1.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void colorButtons(int i, JLabel jl) {
        if (i == 504) {
            jl.setBackground(new java.awt.Color(117, 170, 179));

        } else if (i == 505) {
            jl.setBackground(new java.awt.Color(69, 141, 152));
        }
    }

}
